### ISSUE TITLE
SPAC19A8.16, does not translate properly?

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1007]
https://www.pombase.org/gene/SPAC19A8.16

**Comment by ValWood** [comment]
If you don't have time to look into this now (it is Friday night after all!) , I can let people know that it will be fixed soon.

**Comment by kimrutherford** [comment]
I've swapped back to the previous working version from the 19th while I investigate.

**Comment by kimrutherford** [comment]
Sorry about that.  Thanks for spotting the problem!

The site is on the previous release and I've reverted all the generated files in: https://www.pombase.org/nightly_update/

I've now fixed the problem in the code.  You were right that it was because of the GFF changes.  I noticed a few hours ago that I had got it wrong and I had started on a fix.  But I didn't realise that I broke the website.

Everything should be updated and fixed tomorrow morning.

If you happen to need the updated gene pages (with mangled protein sequences), try the dev site which is still using last night's load: http://dev.pombase.kmr.nz/

**Comment by ValWood** [comment]
I won't  need them its all fine!

**Comment by ValWood** [comment]
Actually if you have a copy of this log file from last night could you send it to me?
https://curation.pombase.org/dumps/latest_build/logs/log.2022-07-19-18-27-04.alleles_of_type_other

Otherwise I'll continue this task until next week.

**Comment by kimrutherford** [comment]
All the old nightly directories are here:
https://curation.pombase.org/dumps/builds/

Here's the log file: https://curation.pombase.org/dumps/builds/pombase-build-2022-07-21/logs/log.2022-07-22-03-00-16.alleles_of_type_other

**Comment by kimrutherford** [comment]
> Everything should be updated and fixed tomorrow morning.

It's all but to normal.  The exons in the GFF files are still number incorrectly.  It should have been fixed today but I forgot to do "git push" last night.  :-)

I'll check the GFF files tomorrow.
