### ISSUE TITLE
can't trace annotation source, spf30

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1010]
I can't trace this NAS annotation
<img width="1309" alt="Screenshot 2022-08-01 at 16 48 28" src="https://user-images.githubusercontent.com/7359272/182188858-54c060bf-3a0a-42bc-bdfb-8cfe36486c47.png">

it is a POmBAse assignment, but it isn't in the legacy file, or in the Canto-external GO data flat files?

**Comment by kimrutherford** [comment]
I've had a quick look and I can't work  it out either.  I'll dig in deeper today.

**Comment by kimrutherford** [comment]
Hi Val.

It took a bit of looking but it's in this file: `pombe-embl/external_data/external-go-data/go_comp.txt`

I missed it the first time because the systematic IDs are capitalised in that file, even the final "c".  So "SPCC1281.02c" is "SPCC1281.02C" in the file.  I was grepping with "SPCC1281.02c" which wasn't found.

**Comment by ValWood** [comment]
I forgot about this. I was also grepping on SPCC1281.02c
