### ISSUE TITLE
remove legacy  tm domain  features from contigs

### ISSUE THREAD

**Issue by Antonialock** [pombase/pombase-chado#1030]
advanced search
protein feature: transmembrane domain vs number of tm domains

949  tm_domain_count(1..30) 
464  transmembrane_helix (SO:0001812)

**Comment by ValWood** [comment]
Since there are only 7 additional annotations from the legacy manual curation, and it is not clear if these are correct
I think we should just remove these annotation from the contigs:


FT                   /controlled_curation="term=sequence feature, transmembrane
FT                   helices; cv=sequence_feature; date=19700101"

**Comment by ValWood** [comment]
This is quick, and I don't think we need to discuss!

**Comment by kimrutherford** [comment]
> I think we should just remove these annotation from the contigs:
>
>     FT /controlled_curation="term=sequence feature, transmembrane
>     FT helices; cv=sequence_feature; date=19700101"

So all "transmembrane helices" or just the ones with that date?

**Comment by ValWood** [comment]
all "transmembrane helices" , they are covered

**Comment by kimrutherford** [comment]
> I think we should just remove these annotation from the contigs:

That's done now.
