### ISSUE TITLE
Alleles not merging in Chado

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#1070]
From https://curation.pombase.org/dumps/builds/pombase-build-2023-03-15/logs/log.2023-03-14-21-44-31.chado_checks.duplicated_allele_names

These alleles are identical in Chado, but should be merged:

```
  fcp1-R271A    SPAC19B12.05c:allele-30 R271A   amino_acid_mutation     15ee54d35bd94b18
  fcp1-R271A    SPAC19B12.05c:allele-4  R271A   amino_acid_mutation     bb6fc09fed8a5c2c
  fcp1-R299A    SPAC19B12.05c:allele-13 R299A   amino_acid_mutation     bb6fc09fed8a5c2c
  fcp1-R299A    SPAC19B12.05c:allele-31 R299A   amino_acid_mutation     15ee54d35bd94b18
```

**Comment by kimrutherford** [comment]
I think the problem is that the allele names in this session don't start with gene names:
https://curation.pombase.org/pombe/curs/15ee54d35bd94b18/genotype_manage/ro

So when they load they don't merge with the alleles from:
https://curation.pombase.org/pombe/curs/bb6fc09fed8a5c2c/genotype_manage/ro

A later process adds the gene name prefix where it's missing, but that code isn't smart enough to then merge the alleles.

I think the best plan is to improve the allele loading code so that it adds the gene prefix as the allele is loaded, rather than leaving it to a later process.

**Comment by kimrutherford** [comment]
I've had a go at fixing this.  I'll check the results on Saturday.

**Comment by ValWood** [comment]
This will be much better. I have been meaning to mention this, it was a pain. ATM, you fix an allele in one session because the author used the description without a name in one session and with a name in another session. For every one you align, you get a bunch more errors.  For example, I already fixed  fcp-R223K this week. I hadn't spotted  R271A  in the logs yet. It doesn't seem too much or a pain to fix one allele, but if they use said allele in 50 multi-gene genotypes it's torture!

<img width="612" alt="Screenshot 2023-03-16 at 07 36 24" src="https://user-images.githubusercontent.com/7359272/225547322-091083ca-6e43-4f68-be36-c00d2b76141a.png">

**Comment by kimrutherford** [comment]
The load failed because of a stray tab in the allele comments file.  I've fixed it for Friday night's load.

**Comment by kimrutherford** [comment]
Hi Val.  The load failed last night because this new feature in chr 2 has no `/systematic_id`:

```
FT   ncRNA           join(1,1..681,192,307,308)
```

**Comment by ValWood** [comment]
oops deleted,  the correct features are there.

**Comment by kimrutherford** [comment]
Hi Val.  I just commented out this line in `pombe-embl/supporting_files/allele_comments.txt` because it doesn't have a reference which causes it to fail to load.

```
plo1-cnp3(fusion)      plo1-centromeric core localized
```

**Comment by kimrutherford** [comment]
The load worked and there are no warnings about duplicate allele names now:
https://curation.pombase.org/dumps/builds/pombase-build-2023-03-19/logs/log.2023-03-18-21-41-44.chado_checks.duplicated_allele_names
