### ISSUE TITLE
GO annotation with missing date and evidence

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#1079]
I've been trying to track down why this annotation has no date or evidence in Chado:

```
SPBC15D4.07c | phospholipid scramblase activity | GO:0017128 | GO_REF:0000024
```

I think the annotation comes from the GOA GAF file.  It looks like the annotation is only partially loading because there is a problem with the extension.  That's a bug that I'll fix - it should be all or nothing.

The annotation extension fails to load because a ChEBI term is missing from Chado.  This warning from the GAF load log file:

```
line 48915: can't find term with ID: CHEBI:57262
```
(https://curation.pombase.org/dumps/builds/pombase-build-2023-04-11/logs/log.2023-04-10-23-33-44.gaf-load-output)

This bug is slightly odd because we've had lots of cases where a annotation extension has problems but I've never noticed a case where the annotation is partially loaded.  I only noticed this case because of some date missing warnings at the end of this log file:
https://curation.pombase.org/dumps/builds/pombase-build-2023-04-11/logs/log.2023-04-10-23-33-44.web-json-write
I've never noticed a warning like this before:
```
WARNING while writing GAF file: date missing from annotation 144283
```

It's a bit weird so I'll investigate.

**Comment by ValWood** [comment]
I'm curious which GOA pipeline this comes from because I wasn't aware of any which included annotation extensions. Could you paste the GAF lin in so I can see the source?

**Comment by Antonialock** [comment]
It's by @sylvainpoux

**Comment by sylvainpoux** [comment]
Hi Val,

I will check these annotations. May I ask you to send me the accessions or PMID? It would help
Thanks
Sylvain

**Comment by Antonialock** [comment]
the accession is Q12142 (cerevisiae propagated) from 33439214.

I think I agree with Val that the different inputs need to be pipe-separated, rather than comma separated (individual statements) .
eg
has_input 1-phosphatidyl-1D-myo-inositol 3-phosphate(3-), part_of/positively regulates BP
.....
"add new independent statement"
has input second chebi ID, part_of/+ve reg
etc

![image](https://user-images.githubusercontent.com/12727506/231114905-86879e6c-a81c-43a7-9f5d-4f7693da154b.png)

**Comment by sylvainpoux** [comment]
Thanks @Antonialock 
The paper shows that ATG9 is a phospholipid scramblasethat can act on various phospholipids and mediate their translocatiom for the assembly of autophagosomes.

I honestly don't know how to pipe-separate substrates... ad I thought that the current syntax was correct.

I can correct this

Thanks for pointing this out

Sylvain

**Comment by Antonialock** [comment]
It's not very obvious but the "+ add new independent statement" button below the extensions will pipe-separate statements rather than comma separate them (I believe!)

**Comment by ValWood** [comment]
The GO documentation for this is poor, in fact there isn't really any, it refers to the protein2GO annotation
https://wiki.geneontology.org/index.php/Annotation_Extension#Dependent_and_independent_statement_in_annotation_extensions
@pgauget maybe this should. be improved on the GO site?

**Comment by ValWood** [comment]
Anyway, I don't think this would stop the  annotation from loading because comma separated are valid in some circumstances if the annotation was a compound annotation. So Kim it is probably your original suggestion that

> The annotation extension fails to load because a ChEBI term is missing from Chado.

I thought we only needed to specify the Chebi terms if they were used  by an ontology term, but not if they are used in an extension? Maybe we need to just add ane ChEBI Ids in extensions to the appropriate file during import (if that is possible). We can chat about this tomorrow.

**Comment by kimrutherford** [comment]
> It looks like the annotation is only partially loading because there is a problem with the extension. That's a bug that I'll fix - it should be all or nothing.

I've fixed that now.

I broke things in: 87419f8eb9f3d894ae2

**Comment by ValWood** [comment]
I don't appear to be able to send e-mail ATM. Trying to send the zoom link...

**Comment by ValWood** [comment]
@Antonialock @sylvainpoux  we get another load error that you can't use "positively_regulates" extension with MF, could you take a look?
https://github.com/pombase/pombase-chado/issues/1081

I think it needs to be 
part_of   because this is a contextual relation, not a causal relation

https://wiki.geneontology.org/Annotation_Relations
You can't do a complete causal relation in the GAF/GPAD format because you can't capture the direction of the connection between activities.

There will be discussion about this in the GO meeting (it's frustrating, and also difficult to understand all the different relationship types.)
