### ISSUE TITLE
Fix line numbers for GOA GAF in log file warnings

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#1086]
The line numbers in the GOA log (`*.gaf-load-output`) are completely wrong.

**Comment by ValWood** [comment]
which lig is this?

**Comment by kimrutherford** [comment]
> which log is this?

It's this one: https://curation.pombase.org/dumps/builds/pombase-build-2023-11-30/logs/log.2023-11-29-21-46-04.gaf-load-output

**Comment by ValWood** [comment]
I always forget this is a log file. Most of it is complex portal stuff, and Uniprot annotations to Tremblentries which can be ignored.
It would be good to figure out which parts I need to find and   separate them out if possible (or just not display the ones of no interest to us)

But I will check this log  soon, because I didn't check it for a long time

**Comment by ValWood** [comment]
ACtually there aren't many issues in here. I will do them when the line numbering is fixed.

Do we need the evidence code cumulative count after every file is loaded?

**Comment by kimrutherford** [comment]
> Do we need the evidence code cumulative count after every file is loaded?

Should I remove it?

**Comment by ValWood** [comment]
I think so. I can't remember why it's in the file...

**Comment by kimrutherford** [comment]
> I think so. I can't remember why it's in the file...

OK.  I've removed them for tonight's load.

**Comment by kimrutherford** [comment]
Fixed for Wednesday morning.

> ACtually there aren't many issues in here. I will do them when the line numbering is fixed.

@ValWood something for you to do?

**Comment by ValWood** [comment]
on my list
