### ISSUE TITLE
is this log file working properly?

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1094]
https://curation.pombase.org/dumps/latest_build/logs/log.2023-06-19-21-13-31.chado_checks.PhenotypesNotInCategory

Running: PomBase::Check::PhenotypesNotInCategory
failed: Check that all phenotype terms have a parent in one of the categories in the website configuration for fission_yeast_phenotype

**Comment by kimrutherford** [comment]
It looks like the code that generates this log file has been broken since I made the changes for this issue: pombase/pombase-chado#952

Luckily there have been no warnings from this chado check since I changed the code.  As of today there is an error to report, which triggered the bug in the reporting of the error ("Use of uninitialized value in concatenation ...").  It's very handy that the bug wasn't silent.

I've fixed the problem and ran the code locally.  We now get a warning (that's unfortunately not very clear): 

```
Running: PomBase::Check::PhenotypesNotInCategory
failed: Check that all phenotype terms have a parent in one of the categories in the website configuration for fission_yeast_phenotype
  FYPO:0007774  PMID:37158439   increased invasive hyphal growth        6
```

What this means is that FYPO:0007774 isn't configured as a Population phenotype or a Cell phenotype so it won't appear on the gene or publication pages.  The "PMID:37158439" is where the term is used and the "6" is the number of annotations.  PMID:37158439 is new on the 19th which is why the error only appeared yesterday.

Is "abnormal hyphal growth" a population phenotype?

**Comment by ValWood** [comment]
I think probably  "abnormal hyphal growth" is difficult to position as cell or population....

It's weird that the term has only just been used since it was created a while ago
I think I will change it to
 pseudohyphal invasive growth
(i'll make it a cell phenotype)

**Comment by kimrutherford** [comment]
I happy that the original problem is fixed.
