### ISSUE TITLE
Identical annotations from Rodriguez et al

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1125]
<img width="1314" alt="Screenshot 2023-11-10 at 13 06 34" src="https://github.com/pombase/pombase-chado/assets/7359272/471e65a3-88cf-4958-a886-b69eb3cf283d">

I don't know if there are more?

CC @manulera

**Comment by kimrutherford** [comment]
They aren't identical in the PHAF file.  They look the same because we're not showing the condition and severity details on the gene pages yet (see https://github.com/pombase/website/issues/2029).

From `pombe-embl/external_data/phaf_files/chado_load/htp_phafs/PMID_34984977_phaf.tsv`:

|Gene systematic ID  |FYPO ID       |Condition                                                                   |Severity               |
|--------------------|--------------|----------------------------------------------------------------------------|-----------------------|
|SPAC4H3.06         |FYPO:0000089  |FYECO:0000137,FYECO:0000211(0.005% (v/v)),FYECO:0000334,FYECO:0000005(32C)|fitness_log2(-0.0445)|
|SPAC4H3.06         |FYPO:0000089  |FYECO:0000137,FYECO:0000211(0.075% (v/v)),FYECO:0000334,FYECO:0000005(32C)|fitness_log2(-0.245)|

--------------------------------------

> I don't know if there are more?

Yep, there are lots of cases like this.  For example SPBC25B2.04c / FYPO:0000087 sensitive to hydrogen peroxide:
 
![image](https://github.com/pombase/pombase-chado/assets/90474/9b0d740f-1fb9-49a9-88ca-9ae4f0872c03)

If we displayed the detail for `+ H2O2` / FYPO:0000087 ("10mM", "8mM", etc.), it would be obvious what's going on.  It would be good to show the matching severity value too.

|Gene systematic ID  |FYPO ID       |Condition                                                           |Severity              |
|--------------------|--------------|--------------------------------------------------------------------|----------------------|
|SPBC25B2.04c       |FYPO:0000087  |FYECO:0000078(2mM),FYECO:0000137,FYECO:0000334,FYECO:0000005(32C)|fitness_log2(-0.223)|
|SPBC25B2.04c       |FYPO:0000087  |FYECO:0000078(4mM),FYECO:0000137,FYECO:0000334,FYECO:0000005(32C)|fitness_log2(-0.272)|
|SPBC25B2.04c       |FYPO:0000087  |FYECO:0000078(6mM),FYECO:0000137,FYECO:0000334,FYECO:0000005(32C)|fitness_log2(-0.393)|
|SPBC25B2.04c       |FYPO:0000087  |FYECO:0000078(8mM),FYECO:0000137,FYECO:0000334,FYECO:0000005(32C)|fitness_log2(-0.555)|
|SPBC25B2.04c       |FYPO:0000087  |FYECO:0000078(10mM),FYECO:0000137,FYECO:0000334,FYECO:0000005(32C)|fitness_log2(-0.716)|

**Comment by manulera** [comment]
Yes! not sure if we created an issue to display this info in the website eventually

**Comment by kimrutherford** [comment]
@ValWood can we close this?
