### ISSUE TITLE
Remove/merge GAF files - go_proc.txt and go_func.txt

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#1127]
From pombase/curation#3613:

One thing we could do is get rid of these 2 files
go_proc.txt and go_func.txt by adding them top the legacy GO files.

In fact, we could do something better.
We could grab ONLY the NAS/IEA data that comes out the post filtering pipeline,
and
add only these to the legacy GO data file (after removing the originals).
This would have the advantage that, if I ever remove a 'masking' EXP
annotation, I don't need to worry about a hidden filtered annotation
reappearing.

**Comment by kimrutherford** [comment]
> We could grab ONLY the NAS/IEA data that comes out the post filtering pipeline, and

All of the annotations are NAS.

It's currently a bit tricky to find the source GAF file of a annotation in code after the filtering.  I think we can fix that though.  I'm working on it now.

**Comment by kimrutherford** [comment]
> It's currently a bit tricky to find the source GAF file of a annotation in code after the filtering. I think we can fix that though. I'm working on it now.

OK, that bit's done.  So on Wednesday I should be able to pull out the annotations from go_proc.txt and go_func.txt that remain after filtering.

**Comment by ValWood** [comment]
I think we can filter NAS from *any* source though. If we have these from another source we can just get rid of them. 
At the moment I delete them if I can (they aren't great annotations because they are unsupported, it really just men's I didn't have time to track a better source.

This means that if a masking EXP annotation is  eventually shown to be incorrect, and I delete it, the lurking NAS can come back and I might not notice it.

Can discuss this morning.

**Comment by kimrutherford** [comment]
I've now removed:
  - `external_data/external-go-data/GO-0023052_gap_filling.gaf.txt`
  - `external_data/external-go-data/go_comp.txt`
  - `external_data/external-go-data/go_func.txt`
  - `external_data/external-go-data/go_proc.txt`

and moved the unfiltered NAS annotations to `supporting_files/legacy_go_annotations_from_contigs.gaf.tsv`

**Comment by ValWood** [comment]
Thank you, will save lots of time!
