### ISSUE TITLE
Use the PRO short name in GPI file

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#1173]
From geneontology/noctua#880

> @kimrutherford can you look into getting these 2 labels into the GPI?

Which ID should we put in each each column?

**Comment by kimrutherford** [comment]
> can you look into getting these 2 labels into the GPI?

From the Noctua issue I can see "Phos:(S450),UnPhos(S412)" as a label.  What's the other one?

https://proconsortium.org/cgi-bin/entry_pro?id=PR_000050512

**Comment by ValWood** [comment]
So a PRO term has:

[Term]
id: PR:000085722
name: histone H3.3, initiator methionine removed K36-trimethylated form (Schizosaccharomyces pombe)
def: "A histone H3.3, initiator methionine removed K36-methylated form (Schizosaccharomyces pombe) whose methylation type is trimethylation. Example: UniProtKB:P10651, 2-136, Lys-37, MOD:00083." [PRO:DAN, PomBase:VW, PMID:37459529]
comment: Category=organism-modification. Requested by=PomBase. Note that in the article cited residue number is different because the initial methionine is not counted.
synonym: "Spom-hht3/InitMet-/K36Me3" EXACT PRO-short-label [PRO:DAN]
synonym: "PRO_0000221367, Lys-37, MOD:00083" NARROW PRO-proteoform-ftid [PRO:DNx]
synonym: "UniProtKB:P10651, 2-136, Lys-37, MOD:00083" NARROW PRO-proteoform-std [PRO:DNx]
intersection_of: PR:000027604 ! histone H3.3, initiator methionine removed K36-methylated form (Schizosaccharomyces pombe)
intersection_of: has_part MOD:00083 ! N6,N6,N6-trimethyl-L-lysine
synonym: "hht3/Me3(K36)" EXACT PomBase_display_name [PomBase:curators]
property_value: pombase_gene_id SPBC1105.11c

we need
synonym: "hht3/Me3(K36)" EXACT PomBase_display_name [PomBase:curators]
to be i nthe GO slot that is displayed

I guess if we have the ID we don't need to include any other labels? byt include "name:" if it is possible.

Doe that make sense?

**Comment by kimrutherford** [comment]
So put:
 - PomBase_display_name in column 2 / DB_Object_Symbol
 - term name in column 3 / DB_Object_Name

?

https://github.com/geneontology/go-annotation/blob/master/specs/gpad-gpi-2-0.md#gpi-columns

**Comment by kimrutherford** [comment]
> term name in column 3 / DB_Object_Name

If we that's needed, there might be an hour of work as we don't currently load the PRO term names into Chado.  That can be fixed though.

Because of this issue: https://github.com/pombase/curation/issues/2851#issuecomment-712472694
we use the `PomBase_display_name` synonym as the term name so it displays nicely.  Example:
https://www.pombase.org/term/PR:000085722

I'll make a change the Chado loading script so that the real term name is stored as a synonym in Chado so it can then be written to the GPI file.

**Comment by kimrutherford** [comment]
> So put:
> -    PomBase_display_name in column 2 / DB_Object_Symbol

I've done that bit because it was quick.

**Comment by ValWood** [comment]
re:So put:
PomBase_display_name in column 2 / DB_Object_Symbol
term name in column 3 / DB_Object_Name
?

I think so...

**Comment by kimrutherford** [comment]
> PomBase_display_name in column 2 / DB_Object_Symbol

That's in last night's load:
https://curation.pombase.org/dumps/latest_build/misc/gene_product_information_taxonid_4896.tsv

> term name in column 3 / DB_Object_Name

That's trickier and I'm trying to work out what's the least hacky solution.

**Comment by kimrutherford** [comment]
> That's trickier and I'm trying to work out what's the least hacky solution.

I can't find a non-hacky solution.  :-)

I've changed the code so that instead of discarding the original term name we now save it as an EXACT synonym with "PomBase_original_PRO_term_name: " as a prefix.  I'm now going to change the code that writes the GPI file to look for that synonym to fill in column 3.

**Comment by kimrutherford** [comment]
> I'm now going to change the code that writes the GPI file to look for that synonym to fill in column 3.

That's done now.  I'll check the result tomorrow.

**Comment by kimrutherford** [comment]
> term name in column 3 / DB_Object_Name

That's done and working.
