### ISSUE TITLE
map all incoming transit_peptide from uniprot to  mitochondrial_targeting_signal

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1202]
map all incoming transit_peptide from uniprot

SO:0001808 | mitochondrial_targeting_signal

(have raised a SO ticket to discuss parentage)

**Comment by kimrutherford** [comment]
I've started a config file containing these sorts of mappings:
`pombe-embl/chado_load_mappings/term_id_mappings.txt`

I'll add a processing step at end of the load that will apply these mappings.

**Comment by kimrutherford** [comment]
> I'll add a processing step at end of the load that will apply these mappings.

Turns out that the code already exists for this because we do the same thing with this mapping file of GO terms:
`pombe-embl/chado_load_mappings/GO_mapping_to_specific_terms.txt`

I've added a step to the load that processes the new mapping file to change SO:0000725 to SO:0001808.  I'll check that on Thursday morning.

To prevent confusion later, I've also manually changed SO:0000725 to SO:0001808 in `pombe-embl/supporting_files/manual_so_term_annotations.tsv`.  The new mapping step with fix those annotations that aren't in the manual SO annotation file (if any).

> `term_id_mappings.txt`

I've just renamed this to: `pombe-embl/chado_load_mappings/generic_term_id_mappings.txt`

**Comment by kimrutherford** [comment]
> I've added a step to the load that processes the new mapping file to change SO:0000725 to SO:0001808. I'll check that on Thursday morning.

I've just finished a local test load and it was OK.

**Comment by kimrutherford** [comment]
That seems OK: https://www.pombase.org/term/SO:0001808

**Comment by ValWood** [comment]
looks good!
