### ISSUE TITLE
DB prefix - CHECK FAILURE:

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#1241]
Is our dbxrefs file up to date?

I get these errors
'with' values that have an unsupported DB prefix - CHECK FAILURE:  expected 0 but got 8
session	pubmed_id	value
  [null]	GO_REF:0000114	ComplexPortal:CPX-558
  [null]	GO_REF:0000114	ComplexPortal:CPX-558
  [null]	GO_REF:0000033	Xenbase:XB-GENE-999731
  [null]	GO_REF:0000033	Xenbase:XB-GENE-999731
  [null]	GO_REF:0000033	Xenbase:XB-GENE-999731
  [null]	GO_REF:0000033	Xenbase:XB-GENE-999731
  [null]	GO_REF:0000033	Xenbase:XB-GENE-999731

but these prefixes are in this file
https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml

**Comment by kimrutherford** [comment]
The dbxrefs file is up to date but the DB names are hard coded into the SQL query for the Chado check:

https://github.com/pombase/pombase-legacy/blob/f5f680825834185a09503fd58d7e2e461148a5b0/load-pombase-chado.yaml#L1132-L1136

It's done this way because it was easier to configure the Chado check like that and the list doesn't change very often.

I've added the missing DB names: https://github.com/pombase/pombase-legacy/commit/f5f680825834185a09503fd58d7e2e461148a5b0
so the check should report no errors in the morning.

**Comment by kimrutherford** [comment]
> 'with' values that have an unsupported DB prefix - CHECK FAILURE: expected 0 but got 8

Those are mostly fixed now.

Except for:

```
'with' values that have an unsupported DB prefix - CHECK FAILURE:  expected 0 but got 1
session pubmed_id       value
  [null]        GO_REF:0000024  UniprotKB:P30825
```

I've just fixed that one in SVN.
