### ISSUE TITLE
Store the curation session IDs of genes as featureprops

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#191]
We current don't store the session ID of genes and alleles.  ie. when a gene or allele is mentioned in a session with should store that session ID as a featureprop.

This is useful so we can query Chado to get the session ID(s) where particular genes or alleles are used.

Original comment by: kimrutherford

**Comment by ValWood** [comment]
@kimrutherford  Is this still required?

**Comment by kimrutherford** [comment]
I think this is still a good idea and we'll need it in future.

**Comment by ValWood** [comment]
OK, I'll put at low priority, you can raise if you need sooner

**Comment by ValWood** [comment]
Put as future. Raise if there are dependencies.

**Comment by ValWood** [comment]
Is this a duplicate of 
   https://github.com/pombase/pombase-chado/issues/323

**Comment by kimrutherford** [comment]
They are a bit different.  This issue was about storing the session ID with genes and alleles.  We now store the session ID of the first session that mentions an allele.  #323 is about storing all the session IDs, not just the first.

I've changed the title of this issue to cover just genes, which currently don't have a session ID or IDs stored for them.

**Comment by kimrutherford** [comment]
Done.

I'll check in the morning.

(I went looking for an old issue and got distracted by other old issues)
