### ISSUE TITLE
logs: report residue = number in logs

### ISSUE THREAD

**Issue by pombase-admin** [pombase/pombase-chado#419]
report a warning for residue = number

for modifications these need to be fixed i.e. residue=1 -> residue=M1

For protein binding, we decided that we would use the normal/abnormal phenotype binding terms to delineate the region of binding (later might be able to do something graphically with these, in sequence context).

For now we can get rid of the legacy stuff.

Original comment by: ValWood

**Comment by kimrutherford** [comment]
> residue=a | residue=b

That's OK as long as you put the extension (if any) twice, like:

> residue=a; added_during(Y) | residue=b; added_during(Y)

This syntax won't work:

> residue=a, residue=b, added_during(Y)

You need semicolons instead like:

> residue=a; residue=b; added_during(Y)

And is that the same as this?:

> residue=a,b; added_during(Y)

I'd prefer that we use one or other syntax, but not both.

I said this above:

> Is this a good summary?:
> modification can have residue= like: "K133" or "K133|K134|..." or "CTD,S2" or "CTD,S2|CTD,S5"

Now I think about it, that syntax won't work as the "|" separates distinct extensions.

You'd need:
    residue= CTD,S2 | residue=CTD,S5
for my last example otherwise the parsing won't work.

And in that case any extension relations would need duplication like:
  residue=CTD,S2; added_during(Y) | residue=CTD,S5; added_during(Y)
which matches how they are storing things in Chado.

This seems to be getting a bit out of hand for something that seems simple.

> i) assume all use of comma in artemis means OR (All of my legacy stuff) and remap

That's going to be hard work to do automatically because if comma means OR, then this:
  residue=a,b;  added_during(Y)

will have to be changed to:
  residue=a;  added_during(Y) | residue=b;  added_during(Y)

Alternatively, if this residue stuff is just for displaying on the gene pages rather than querying in Chado (or Ensembl) we could just use a syntax like:
  "residue=CTD,S2 OR CTD,S5;  added_during(Y)"
then the residue string can just be stored as a string in Chado and Ensembl and displayed as-is on the gene pages.  That's probably the easiest short/medium term plan.

(Sorry that was long winded and confusing.  Maybe we should have a rather tedious chat about it sometime)

**Comment by mah11** [comment]
I wouldn't worry about doing anything automatically for this — the numbers are so small that we can convert manually to whichever syntax we choose. In fact, I'll make an executive decision to use 

  residue=a; added_during(Y) | residue=b; added_during(Y)

and will update any that don't already fit. It won't be a big job, because most of the "residue=" entries in Artemis are single residues without any other extensions anyway.

This one in particular is a single case, with complications explained in https://github.com/pombase/curation/issues/139. I'll just fix it now to 

    residue=CTD,S2; added_by(PomBase:SPBC32H8.10) | residue=CTD,S5; added_by(PomBase:SPBC32H8.10);

It doesn't have any added_during(Y) bits.

**Comment by mah11** [comment]
One more quick q: are ranges still OK, e.g. "residue=P16-R20"?

**Comment by kimrutherford** [comment]
> One more quick q: are ranges still OK, e.g. "residue=P16-R20"?

Yep!

**Comment by mah11** [comment]
Excellent. In that case the fixing is indeed doable. Could even be finished today.

**Comment by mah11** [comment]
Now pretty much fixed. For the CTD stuff I changed to residue=CTD_S2 etc. to keep the comma available for "and" in case we ever need it.

Radical idea: close this, and open a new ticket if we need any more changes to what's flagged in logs?

**Comment by kimrutherford** [comment]
Thanks for the fixes.

I haven't actually added any syntax checking to the value of the residue= qualifiers yet.  So you can put "residue=aardvark" and the loader will happily store that.

**Comment by ValWood** [comment]
I'm going to close this and open a new ticket for the syntax checks required. I think thats it? If anything else remains. please open a new ticket.
