### ISSUE TITLE
problem with 'existing' allele which should not exist

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#488]
I have the error

warning in 6f1818d4183cd160: trying to store an allele with the name "Xba" but the name exists with different case: "xba" (from session 6f1818d4183cd160)

But this is referring to an allele which I fixed earlier in the same session? It shouldn't exist?

**Comment by ValWood** [comment]
![xba xba](https://cloud.githubusercontent.com/assets/7359272/9703131/f3a8c934-5470-11e5-9100-f5226782aa42.jpg)

**Comment by ValWood** [comment]
![image](https://cloud.githubusercontent.com/assets/7359272/9703133/09a5f446-5471-11e5-8f1c-4e09c23170b5.png)

**Comment by ValWood** [comment]
I replaced the Xba by the lower case version?

**Comment by kimrutherford** [comment]
The Xba allele is still there because the genotype is still in the session that uses it:
  http://curation.pombase.org/pombe/curs/6f1818d4183cd160/feature/genotype/view/2/ro

The genotype doesn't have any phenotypes so it doesn't show up on the front page.   The loader currently tries to load all genotypes and their alleles from the session even if they don't have annotation.

**Comment by ValWood** [comment]
Hmm, how best to handle this?
Should I just go in and delete the genotype. I think we were going to have a warning for unused genotypes? @mah11  and @Antonialock  any preferences how we should do this? I am worried I might overlook something...
v

**Comment by ValWood** [comment]
anyway the  problem in the  logs is solved. I'll keep this ticket open for feedback and then open the appropriate ticket with the preferred behaviour on Canto tracker.

**Comment by kimrutherford** [comment]
How about we start we a warning about it when you're in approval mode?  We could also add something to the chado checks.

**Comment by kimrutherford** [comment]
I've added a warning to Canto.  When you're approving a session it will tell you if there are genotypes with no annotations.

pombase/canto@2b50cda98deb5c553f2fa1651969e1bef2fbedbc

**Comment by ValWood** [comment]
that should  do it. we can do more checks  later if necessary

**Comment by mah11** [comment]
A warning sounds fine to me (although I suspect it's probably safe to delete unused genotypes).

For the specific allele that led to this ticket, though, I think it actually should be "Xba", not all lower case. The allele names in the paper are "Xba::" and "Sma::", after the restriction sites where they made those deletions. I removed the "::" parts because having them at the end of the names was screwing up loading for Mark, but the case should have stayed as it was because that's closer to the original restriction enzyme designations.

**Comment by ValWood** [comment]
#965

**Comment by mah11** [comment]
If it's on the same tracker, you only need # plus the ticket number.

Copy the whole URL for a ticket on any other tracker (whether it's a pombase one or not), and GitHub wil magically shorten what it displays as the link:

https://github.com/pombase/canto/issues/965

**Comment by ValWood** [comment]
so thats what I did above?

**Comment by mah11** [comment]
No, you just did #-plus-number for a ticket in the canto tracker (this is the pombase-chado tracker). IOW, you tried the within-a-tracker format when you needed the different-tracker format.

**Comment by ValWood** [comment]
got it, I thought these were all canto tracker

**Comment by ValWood** [comment]
pombase-chado/issues/965

**Comment by ValWood** [comment]
ffs. SORRY!

**Comment by ValWood** [comment]
pombase/canto#965

**Comment by mah11** [comment]
:D

**Comment by ValWood** [comment]
I really am doing everything wrong today. Worse then normally.....I think I'm going to step away from the keyboard for a little while...
