### ISSUE TITLE
can we omit the underscore from "disease_associated"?

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-chado#498]
For Jira PBs2395 (https://www.ebi.ac.uk/panda/jira/browse/PB-2395), it would help immensely if the PBO:0000050 term name had a space instead of an underscore (i.e. 'disease associated' instead of 'disease_associated'). Can this change be made at the Chado level? Would curators have to do anything?

**Comment by kimrutherford** [comment]
I'm a bit confused by this.  I can change "disease_associated" to "disease associated", but it's not a term name, it's a CV name:
  http://curation.pombase.org/pombe/view/object/cv/49?model=chado

I guess PBO:0000050 is a typo?  It's:
  http://curation.pombase.org/pombe/view/object/cvterm/60585?model=chado

The Jira ticket mentions PBO:5000000, but there is no term with that ID in Chado.  I assume it's auto-generated by the Ensembl load.

**Comment by kimrutherford** [comment]
I've had a look at the loading code for CV names.  The easiest way to make this change is to change all of the CV names to have spaces instead of underscores.  I could do a special case just for disease_associated, but that doesn't seem right.  Changing to spaces for all would likely have some knock-on effects for the Ensembl load so it's up to Mark.  Changing just disease_associated wouldn't be such a problem.

@markmcdowall

**Comment by markmcdowall** [comment]
Found the source. I generate an OBO file for loading all the ontology terms from the PBO. For the flat controlled vocabs I had to create a head node.

I have found a way around it in the autocomplete
