### ISSUE TITLE
Incorrectly loaded with/from values

### ISSUE THREAD

**Issue by markmcdowall** [pombase/pombase-chado#504]
The loading of the with/from values seems to have failed. In previous releases where there have been multiple with/from gene stable_ids these have existed as separate rows. In Chadov56 they are now getting included as a single row with comma separation.

```sql
SELECT
  f1.uniquename,
  f1.feature_cvterm_id,
  f1.value,
  f2.uniquename
FROM
  (
    SELECT
      f.uniquename,
      fcp.value,
      fc.feature_cvterm_id
    FROM
      feature f
      JOIN feature_cvterm fc ON (f.feature_id=fc.feature_id)
      JOIN cvterm fcc ON (fc.cvterm_id=fcc.cvterm_id)
      JOIN dbxref fccx ON (fcc.dbxref_id=fccx.dbxref_id)
      JOIN db fccd ON (fccx.db_id=fccd.db_id)
      LEFT JOIN feature_cvtermprop fcp ON (fc.feature_cvterm_id=fcp.feature_cvterm_id)
      LEFT JOIN cvterm fcpt ON (fcp.type_id=fcpt.cvterm_id)
    WHERE
      fcpt.name IN ('with') AND
      fcp.value LIKE 'PomBase:%') AS f1
  LEFT JOIN feature f2 ON (f1.value='PomBase:' || f2.uniquename)
WHERE
  f2.uniquename IS NULL;
```

   uniquename   | feature_cvterm_id |                                        value                                        | uniquename 
----------------|-------------------|-------------------------------------------------------------------------------------|------------
 SPAC2G11.12.1  |              4515 | PomBase:SPBC336.01,PomBase:SPAC20H4.07                                              | 
 SPBC16E9.18.1  |             44625 | PomBase:SPAC25B8.03,PomBase:SPAC31G5.15                                             | 
 SPBC16E9.18.1  |             44627 | PomBase:SPAC25B8.03,PomBase:SPAC31G5.15                                             | 
 SPAC1610.03c.1 |             10467 | PomBase:SPBC16A3.05c,PomBase:SPAP27G11.10c                                          | 
 SPAC2G11.12.1  |              4519 | PomBase:SPAC16A10.07c,PomBase:SPBC660.13c                                           | 
 SPAC2F3.01.1   |             23486 | PomBase:SPCC4F11.04c,PomBase:SPAC17G8.11c                                           | 
 SPAC17H9.19c.1 |             11904 | PomBase:SPAC29B12.03,PomBase:SPAC17H9.10c                                           | 
 SPCC4F11.04c.1 |             70773 | PomBase:SPAC2F3.01,PomBase:SPAC17G8.11c                                             | 
 SPCC4F11.04c.1 |             70774 | PomBase:SPAC2F3.01,PomBase:SPAC17G8.11c                                             | 
 SPAC3A12.09c.1 |              8293 | PomBase:SPAC3A12.09c,PomBase:SPCPB16A4.05c,PomBase:SPAC29A4.13,PomBase:SPAC1952.11c | 

In Chadov55 these annotations where on separate row:
```sql
SELECT
  f1.uniquename,
  f1.feature_cvterm_id,
  f1.value,
  f2.uniquename
FROM
  (
    SELECT
      f.uniquename,
      fcp.value,
      fc.feature_cvterm_id
    FROM
      feature f
      JOIN feature_cvterm fc ON (f.feature_id=fc.feature_id)
      JOIN cvterm fcc ON (fc.cvterm_id=fcc.cvterm_id)
      JOIN dbxref fccx ON (fcc.dbxref_id=fccx.dbxref_id)
      JOIN db fccd ON (fccx.db_id=fccd.db_id)
      LEFT JOIN feature_cvtermprop fcp ON (fc.feature_cvterm_id=fcp.feature_cvterm_id)
      LEFT JOIN cvterm fcpt ON (fcp.type_id=fcpt.cvterm_id)
    WHERE
      fcpt.name IN ('with') AND
      fcp.value LIKE 'PomBase:%') AS f1
  LEFT JOIN feature f2 ON (f1.value='PomBase:' || f2.uniquename)
WHERE
   f1.feature_cvterm_id=36334;
```

  uniquename   | feature_cvterm_id |        value        | uniquename  
---------------|-------------------|---------------------|-------------
 SPBC1706.01.1 |             36334 | PomBase:SPCC895.05  | SPCC895.05
 SPBC1706.01.1 |             36334 | PomBase:SPCC1223.06 | SPCC1223.06

**Comment by markmcdowall** [comment]
This is in JIRA as PB-2459

**Comment by kimrutherford** [comment]
Thanks Mark.

I've tracked down the problem.  There are lots of "with" fields with multiple values in the flat files but the values are separated but "|".  A few have slipped in since the last release with commas separate the fields instead.  The Chado loader is being dumb about it and just storing whatever it gets after split at each "|".  I'll fix the flat files and change the code to do some basic checking to make sure the field value looks valid.

I'll need to do a new release.

**Comment by mah11** [comment]
Bear in mind that both comma- and pipe-separated "with" entries are now allowed by GO, because they have different meanings. Pipe-separated entries can be split into separate rows, but if the entries are comma-separated it means they have to stay together (it's one  annotation saying that whatever is inferred from, e.g., interaction with both A and B at the same time).

I don't think we should have very many intentionally comma-separated "with" entries, and it's not a bifg deal if they get handled properly later than v56 or even 57. But it's gotta happen eventually 'cos the greater GOC has gone that way.

**Comment by markmcdowall** [comment]
In which case this will need to be defined in the Chado db then subsequently in the ensembl db.

**Comment by ValWood** [comment]
I don't think we should  use "|" separated...we should use separate rows for separate annotations.

As far as I'm aware we don't really need comma separated  except for 
GO:0030674 protein binding, bridging IPI annotations

For ISO/ISS we only need one ID (no point adding loads, just use  a single experimentally characterised example....

**Comment by mah11** [comment]
I agree, we can use one ID with any annotation using ISS-branch evidence. We're also effectively doing separate rows for all new pipe-separated 'with' entries for IPI and IGI, and I think the legacy ones in the contig files have been retrofitted.

We will need comma-separated for a few IPI and IGI annotations, for the occasional cases where it's a three-way interaction that supports the annotation.

There are also a few pipe-separated 'from' entries for some IC annotations in the contig files. I wonder if GO should switch to comma-separated for these cases, because AND is the intended meaning (tho their documentation still has pipes in its examples).

**Comment by ValWood** [comment]
Excluding GO, these are the only pipe separated ones. I'm going to go in and reduce all of these to a single entry now as there are so few......

Val-Woods-MacBook-Pro:Desktop val$ cut -f 8 pombase-build-2015-11-09-v1-l1.gaf |more | grep "|"  | grep -v GO
PomBase:SPBC336.01|PomBase:SPAC20H4.07
SGD:S000005234|UniProtKB:P40938
PomBase:SPBC15D4.03|PomBase:SPBC31F10.13c
PomBase:SPCC126.02c|PomBase:SPBC29A10.05
SGD:S000003677|SGD:S000006074

**Comment by kimrutherford** [comment]
> Bear in mind that both comma- and pipe-separated "with" entries are now allowed by GO

Ah.

I've just reverted all my "fixes" to the contig files.

> In which case this will need to be defined in the Chado db then subsequently in the ensembl db.

I'll go back to storing the ones with commas as-is, in which case we might not need a new release.  How easy is it just to ignore those "with" properties with comma in for this release?  We can worry about what the real fix is later.  If it's a problem, I'll just delete them for the release.

**Comment by markmcdowall** [comment]
Kim: For the OR annotations could these not just go in as an identical annotation with its own ID, but only considering just the AND genes?

Or are we going to have some rather cases with nested logic?

**Comment by kimrutherford** [comment]
> For the OR annotations could these not just go in as an identical annotation with its own ID,
> but only considering just the AND genes?

I think so but I think it's worth having a quick chat about on the next Skype call to make sure there are no surprising cases to consider.

**Comment by mah11** [comment]
There will be no nesting for this, and it's my understanding that OR annotations do go in as separate lines now. So the only change(s) required is/are to accommodate comma-separated AND entries. I can't imagine needing to mix AND and OR in one annotation (anything with both pipe and comma should get throw back to curators in an error log).

**Comment by kimrutherford** [comment]
Mark: How easy is it just to ignore the "with" properties with comma that are causes warnings?  Should I do another load and remove them?

> it's my understanding that OR annotations do go in as separate lines now.

In Chado we currently store one annotation and if there are multiple withs separated by "|" they get stored as properties on that one annotation.  Those end up in the GAF file "with" column like "PomBase:SPAC25B8.03|PomBase:SPBC16E9.18".

Should we be storing each annotation with one "with" when they are ORs and export a separate annotation line for each one?

**Comment by mah11** [comment]
> Should we be storing each annotation with one "with" when they are ORs and export a separate annotation line for each one?

For the GAF it doesn't matter; it would mean the same thing either way. So do whichever is easier for Chado storage and/or the release pipeline ...

**Comment by ValWood** [comment]
Personally, I think its easier if we export separate lines for separate annotations in the GAF. Less syntax for users to be aware of....

**Comment by markmcdowall** [comment]
From what has been said probably the ideal solution would be to store AND linked featuers as their own value/rows in the feature_cvtermprop table (multiple genes therefore multiple rows) linked to the same feature_cvterm_id, where as OR related features should have their own feature_cvterm_ids with their own AND linked features.

This would make it simpler for storage and retrieval.

Perhaps a fresh load may be best to avoid potential code mix-ups.

**Comment by ValWood** [comment]
Mark can you confirm, do you want an new Chado build ?
I don't  now if this will help....
There are some commas and some pipes.  We will get rid of pipes in this field (even though they are allowed by GO).

In the GAF for the current release, there are 34 with fields with commas. Commas are allowed and represent a "compond annotation" these should be diplayed just as the with filed is displayed currently

140 annotations are pipe separated. These will disappear once GO have updated their scripts and we can make the changeover (most are supporting IC from and will change to commas).

For now,  just treat commas and pipes the same, and display exactly the same way as you were displaying previously. After the changes we will only have commas and these will be displayed just as pipes were displayed previously.
i.e.	fbh1, rad57

Does that make sense?
Nothing is different  about the display, its just that the symbol we have used has changed.

**Comment by mah11** [comment]
Note to self: update IC pipe to comma when we're confident GO is ready; also update gaf-version tag when committing GAF to GO

**Comment by markmcdowall** [comment]
Depends on what is going to happen with the loading.

Previously I have retrieved data from the Chado db based on the feature_cvterm_id, which represents a single line in the GAF file. This has a 1:n link with the feature_cvtermprop table that contains the genes and other annotation extensions. In each case in the feature_cvtermprop table there is 1 gene per row. This is still the case, but there are now rows with comma separated terms as well.

I can split by comma as a hack for this release and include them as with x, with y, with z. But this will also include any extra with a, with b and with c if there are other rows in this 1:n relationship that also link to genes in the same with/from relationship.

That said, ideally it would be best to fix this at the Chado end first by placing each of the comma separated features as separate rows within the feature_cvtermprop table and the OR relationships having different feature_cvterm_ids.

Do you want me to go ahead and try the hack for this release? If Kim could also try regenerating the db with a modified loader that would be great as if the loading does not work with the hack then we can fall back to the fixed Chado db.

**Comment by ValWood** [comment]
Part of the problem is that we can't fix yet fully, because the GO loading script needs changing by Mike Cherry and he is on holiday.

There are so few annotations supported by with or from. If you treat them all as commas, this will work. Eventually everything will be commas.

The comma means that the annotation should not be 'split'. A comma indicates a COMPOUND annotation. Both pieces of information are required for the single annotation.
They should be displayed *exactly *as you display the with from field now.

In summary:
1. Treat everything as a comma, eventually everything will be a comma (not a pipe)
2. The comma means 'compound' annotation
3. The display will not change from how it is currently. The  annotation have exactly the same meaning that they used to have. The only difference is that to make the GO files with field consistent with the 
annotation extension filed the comma is used as the separator for conpound annotations instead of the pipe.
4.  If these annotation do end up not being displayed for this release it isn't a huge issue (its a small number of annotations)

Kim, if you could do the fix as a fallback that would be great. We'll be occupied with the workshop until late tomorrow afternoon.

Thanks

Val

**Comment by kimrutherford** [comment]
> Kim, if you could do the fix as a fallback that would be great.

I'm having a bit of trouble keeping up.  Which fix do you mean?  It looks like you've removed all the commas from the contig file with= qualifiers, which is great.  I need to fix the loader to store the pipe separated withs sensibly in Chado.  Is that the fix you mean?

**Comment by ValWood** [comment]
I'm not sure. I am confused too....

**Comment by markmcdowall** [comment]
I thought that the fix was going to be that the OR annotations would have their own separate feature_cvterm_id and that the AND linked terms would go in as a separate row in feature_cvtermprop table.

**Comment by mah11** [comment]
For v57 onwards, the Chado loader will need to cope with comma-separated 'with/from' entries (GO GAF column 8). There are a bunch of warnings in the latest qualifier_problems.txt log about the ones that have commas, and there will soon be more when I update the annotations with IC evidence and multiple 'from' entries.

**Comment by kimrutherford** [comment]
oliver0 isn't being upgraded until Friday so I've made the change to handle commas and the load is loading.  We should be able to do a Chado release this week.

**Comment by kimrutherford** [comment]
The load looks fine and the qualifier_problems.txt log file is now empty.  I'll do a final load tomorrow if there are no other problems.
