### ISSUE TITLE
exported PHAF is suspiciously tiny

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-chado#516]
BIG problem: The PHAFs from the last couple of builds are only 1.4K zipped, or about 116 lines unzipped.

Sorry, I should've noticed this a lot sooner -- the last sensibly sized PHAF is in pombase-build-2016-01-04-v2-l1  (pombase-build-2016-01-04-v2-l1.phaf.gz	2016-01-06 21:15	513K).

**Comment by kimrutherford** [comment]
Thanks for spotting that. There are some warnings in the export_warnings file that might be related.

**Comment by kimrutherford** [comment]
I've tracked down the problem.  The export was failing because there are now some annotations stored in Chado that don't have any metadata ("props" in Chado speak) like date and evidence.  They are mostly from the contig files.

It's an easy to fix dumb bug that no metadata was causing problems.

It took me a while though to work out why this has started to be a problem now.  I think it's because of fixing #514.  Which means that there are some annotations that had date as the only metadata but now have none.  Here's an example from chr1:

    FT                   /controlled_curation="term=phenotype, DNA damage
    FT                   checkpoint override in response to caffeine abolished;
    FT                   db_xref=PMID:10224243; cv=phenotype; date=19700101"

The date=19700101 is now not stored and the PMID is not stored as a Chado prop.

So I'll commit the easy fix after a quick test.

**Comment by kimrutherford** [comment]
The PHAF file is back to normal size in the latest load.
