### ISSUE TITLE
do we allow extensions generally on 'controlled curation'

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#517]
I just did this...can we allow them?
No hurry...

/controlled_curation="term=subunit composition, homomeric(4); annotation_extension=occurs_at(GO:0044732); db_xref=PMID:26256832; date=20160119"
/controlled_curation="term=subunit composition, homomeric(2); annotation_extension=occurs_at(GO:0000777); db_xref=PMID:26256832; date=20160119"

**Comment by mah11** [comment]
Sounds fine in principle to be able to extend these, tho of course Kim will have to say whether it's possible just now or, if not, what needs changing to load them.

One specific note, though: occurs_at is NOT an allowable relation for subunit composition extensions, because "occurs" can only be used with an event (e.g. GO MF or BP). The composition of a complex is not an event (though complex assembly is).

I found a relation in RO that looks like it would work well for these: located_in

**Comment by ValWood** [comment]
changed to 'located_in'

**Comment by kimrutherford** [comment]
>  just did this...can we allow them?

I think though.  Tomorrow's log file will tell us for sure.

**Comment by ValWood** [comment]
If they end up in the logs not urgent to fix, just nice to know we can capture eventually

**Comment by kimrutherford** [comment]
It didn't load:
  failed to add annotation extension to SPAC25G10.07c <-> homomeric(2): occurs_at() not allowed because no extension relations are configured for subunit_composition

I've changed the config to allow that extension:
  https://github.com/pombase/pombase-legacy/blob/master/load-pombase-chado.yaml#L185

pombase/pombase-legacy@29087f36f1c68831e571d044aff7a32831bf7594

**Comment by ValWood** [comment]
so do we now just need to track if this makes it thorough to the gene pages?

**Comment by mah11** [comment]
I've just corrected the config.

Getting these extensions to show up on gene pages will require a new ticket for Mark on Jira.

**Comment by ValWood** [comment]
opened a jira ticket.
so closing this ?
