### ISSUE TITLE
Average number of annotations

### ISSUE THREAD

**Issue by Antonialock** [pombase/pombase-chado#523]
Hi Kim, 

COuld you rerun the query for average number of annotations per paper per year, same as in #455 thanks!

**Comment by kimrutherford** [comment]
Hi Antonia.

I've got the numbers from Chado v57.  They are a different than last time.  That might be because I forgot to include interaction annotations last time.  Some of the averages have gone down which might be because we're now including papers that had only a few interaction annotions.

https://www.dropbox.com/s/363ldm9b9i91g2s/annotations_per_paper_per_year_inc_interactions.csv?dl=0

And here are the average annotations per paper in 5 year bins (1995-1999,2000-2004, etc).  The "2015" bin is just papers from last year.  If you'd like the bins to be 1996-2000, 2001-2005 instead, let me know.

https://www.dropbox.com/s/t3bkr90ry7vghp9/annotations_per_paper_per_year_inc_interactions_bins.csv?dl=0

**Comment by kimrutherford** [comment]
I should say that these are all the annotations in Chado from every source for each paper.  Is that what you're after?

**Comment by Antonialock** [comment]
That sounds good, will let you know tomorrow if there are any problems :)

**Comment by ValWood** [comment]
Yep, I'm not sure we want to include *everything* from bioGRID

There may be a couple of publications that we want to filter from the interactions (some of the huge mass spec where they reported everything, and Colm Ryan  genetic interaction screen which are really HTP....I think we will have a better idea when we see the graphs ......

If it only includes the interactions curated in canto, it should be fine

**Comment by kimrutherford** [comment]
> If it only includes the interactions curated in canto, it should be fine

OK, I've updated the links above to include only Canto annotations.

**Comment by kimrutherford** [comment]
> OK, I've updated the links above to include only Canto annotations.

Ah, I misread that - so include all ontology annotation but only include interactions from Canto?

**Comment by Antonialock** [comment]
yeah that sounds right

On Wed, Feb 17, 2016 at 8:47 PM, Kim Rutherford <notifications@github.com>
wrote:

> OK, I've updated the links above to include only Canto annotations.
>
> Ah, I misread that - so include all ontology annotation but only include
> interactions from Canto?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pombase/pombase-chado/issues/523#issuecomment-185396386>
> .
>



-- 
Antonia Lock, PhD
PomBase Biocurator, http://www.pombase.org
Department of Genetics, Evolution and Environment,
The Darwin Building,
University College London
London WC1E 6BT, UK

**Comment by kimrutherford** [comment]
OK, here are the annotations per pub per year, but with interactions only from Canto:
  https://www.dropbox.com/s/363ldm9b9i91g2s/annotations_per_paper_per_year_inc_interactions.csv?dl=0

and the same, binned in 5 year intervals:
 https://www.dropbox.com/s/t3bkr90ry7vghp9/annotations_per_paper_per_year_inc_interactions_bins.csv?dl=0

Let me know if that's OK.
