### ISSUE TITLE
purge old ontology terms from chado

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#563]
Like here:
https://curation.pombase.org/pombe/view/object/cv/21?model=chado

How would we do this? I think longer term it is better if these don't hang around

It can be confusing if we want to share these links ever, (and for us)
https://github.com/pombase/pombase-chado/issues/561

**Comment by kimrutherford** [comment]
Do you mean the ones with zero features?

To help with Ensembl loading we try to keep all PBO IDs stable.  If we loaded everything from scratch for each release the IDs would change each time.  Instead, after each Chado release we dump an OBO file containing all the PBO terms and load it into the next Chado.  That keeps the IDs the same but the down side is the terms that are no longer needed hang around.

The fix is to remove the term from the OBO file generated after v60.  The file is here on oliver0:
 /var/pomcur/sources/pombase/pombase_terms-v60.obo

I'll remove those terms from the link above.  Let me know if you see others the need removing.

**Comment by ValWood** [comment]
thats ok for now
