### ISSUE TITLE
log file errors

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#569]
You might know about this, PHAF files are giving the following errors.

more the one relation cvterm returned for part_of:
terms: BFO:0000050 and _global:part_of

(Does anyone know who is on log duty for the next update?)

v

**Comment by mah11** [comment]
Kim has known about these errors for two months. It's an OBO relations thing that makes all of our heads melt a bit. It's being handled in https://github.com/pombase/chobo/issues/5.

I'm not "officially" on logs (I do the integer multiples of 3) but I've been looking occasionally ever since the monthly-ish release schedule broke down.

**Comment by kimrutherford** [comment]
> You might know about this, PHAF files are giving the following errors.

Yep, we've seen those before.  They're annoying but they are just warnings.

**Comment by ValWood** [comment]
OK, I will keep looking at the logs too, will have a quick go now....
