### ISSUE TITLE
Allow NOT annotation to taxon restricted terms

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#590]
one example
NOT c57f22a897472fa7 - GO:0009008

pombe does not have DNA methytransferases, but orthologs of this protein have this activity.

**Comment by ValWood** [comment]
won't worry about this  until we have an example

**Comment by kimrutherford** [comment]
> won't worry about this until we have an example

It's a bit awkward to do at the moment because we are now loading just the pombe GO subset.  That'd good because we get a warning if we try to use a non-pombe term.  To allow for NOT we'd need to load the full ontology but add a property to the pombe-only terms, then check for the property before storing a non-NOT annotation.

**Comment by ValWood** [comment]
Its not a big deal. If we know enough about the biology of an organism to know that a term can be taxon restricted, we should not need NOT annotations to support this (IMHO).

**Comment by ValWood** [comment]
I'm closing this, I think we can handle at curation level.

I came across this because I am looking for a ticket that I am sure exists. It is about handling "NOT" annotations correctly.

It affects the "unslimmed" but annotated terms.
