### ISSUE TITLE
curation stats query

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#605]
Noticed while preparing my talk:
Is there an obvious reason why

1. Number of community curated papers is 410
2. Number of papers assigned to community and finished is 469

![discrepancy](https://cloud.githubusercontent.com/assets/7359272/21677506/687df1f8-d332-11e6-9711-3591c0574a90.jpg)

**Comment by kimrutherford** [comment]
Unfortunately I think the 410 is right and the 469 is too high.

The 469 currently includes sessions that were assigned to a community curator but were finished (or completely done) by one of you three.  Here's an example where all the annotation was done by Antonia but it's included in the 469:
  https://curation.pombase.org/pombe/view/object/curs/1408?model=track

It's easy to change things so that only it's considered a community session only if the current curator at the time of submission was from the community.

**Comment by ValWood** [comment]
That would make sense. I think these must be sessions that were sent out but then subsequently  taken back by us. We can exclude these from the count. We might need to re assess this though if we end up doing a lot of sessions which could have been community curated once we have cleared the back-log.
Although I am surprised it is 59 already.
One possibility is that these were papers from the pilot. Maybe?

In fact lets not worry about it for now, we can decide what to do later.

**Comment by ValWood** [comment]
I'll close this.

Not to all. If you"steal" a paper that was assigned to the community, but has not been sent out for long, you can delete the session and make a new one.
