### ISSUE TITLE
report pipe separated "with" field in logs

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#608]
we don't use, as we do these as separate entries in canto.

**Comment by ValWood** [comment]
scub above. in artemis. don't curate these in canto as yet.

probably not so much that we do as separate entries as we only need  one e.g to support an annotation.

**Comment by mah11** [comment]
We curate single 'with' entries in Canto, so we can do the separate annotations that mean the same thing as piped withs.

There is a ticket (#1094) open to add support for comma-separated 'with' entries.

We can't do any 'from' entries in Canto yet because it doesn't do IC evidence. When it does, AND and OR entries will automagically be supported as for 'with'.

**Comment by ValWood** [comment]
I think I meant in Artemis. There are none anyway...
