### ISSUE TITLE
handling output_of in canto, chado and Web pages

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#613]
Using the "output_of" relation, eg,

decreased cell wall polysaccharide level	FYPO:0002266	output_of	abnormal cell wall biogenesis	FYPO:0000174

we should be able to say that 
all genes annotated to FYPO:0002266
decreased cell wall polysaccharide level	
are also annotated to
abnormal cell wall biogenesis	FYPO:0000174

This does not appear to be the case at the moment:

![inheritance of output of](https://cloud.githubusercontent.com/assets/7359272/23207941/14873166-f8eb-11e6-99c3-cb45ebf983be.jpg)

**Comment by ValWood** [comment]
In Canto, I do see as a descendant, so this is fine
![canto](https://cloud.githubusercontent.com/assets/7359272/23208091/9cb7578c-f8eb-11e6-88a9-6aa0b35fa62f.jpg)

Just need to make sure the same is reflected in chado, and on gene pages?

**Comment by ValWood** [comment]
So, when this is working, we will  also see rap1 and bqt4 in this list:
http://pombase2.aska.gen.nz/term/FYPO%3A0001515
abnormal telomere tethering at nuclear periphery

**Comment by kimrutherford** [comment]
This is the current list of relations loaded into Canto:

- is_a
- has_output
- output_of
- part_of
- has_part
- regulates
- negatively_regulates
- positively_regulates

Should we use all of those when finding inferred annotations for the website?

The current list used by the website is:

- is_a
- part_of
- regulates
- has_part

All of the relations used by Canto (and more) are in Chado because we load the full OBO file for each ontology.

**Comment by ValWood** [comment]
We don't use has_part for GO, but we use for phenotypes.
We should use all regulates relations (but regulates might subsume both +and - anyway?)

has_out and output_of should mirror Artemis behaviour. There is something  odd about the interpretation, (I believe you treat the relationship in an inverse way to make an inference).
@mah11  could you link to the ticket where you explained correct behavior previously? 

Does this work for all phenotypes (cell and population)? Or was there some exception? (normal)? I can't remember but I had a feeling there was something else....

**Comment by ValWood** [comment]
another e.g. for checking
http://pombase2.aska.gen.nz/term/FYPO%3A0000190

would also list "mislocalized actin cortical patches" (21 additional genes which are not otherwise annotated to  FYPO:0000190 - abnormal actin cortical patch localization)

**Comment by mah11** [comment]
As noted on the related FYPO ticket (https://github.com/pombase/fypo/issues/2963), first we have to confirm that the question is only about output_of, and if so, correct the ticket title.

Once we have that cleared up, I'll have some follow-up questions.

**Comment by mah11** [comment]
Canto behavior is addressed in https://github.com/pombase/canto/issues/1307.

**Comment by ValWood** [comment]
I am only looking at is about "output_of"

**Comment by mah11** [comment]
> has_output and output_of should mirror Artemis behaviour. 

I have no idea what this refers to.

> (normal)?

For normal phenotypes, I removed the has_part links because we couldn't accommodate the way Canto was handling them. (For example, it would be biologically and ontologically correct to say FYPO:0001007 normal mitosis has_part FYPO:0004396 normal mitotic spindle elongation, we don't so that Canto won't offer confusing suggestions.)

**Comment by mah11** [comment]
Possibly quixotic attempt to summarize and reduce confusion ...

Canto

* I'm pretty sure Canto is doing what we want with GO terms and relations. Drill-down options should use is_a, part_of, and the regulates trio. If we do spot any problems, we'll open a Canto ticket.

* Canto is also OK for FYPO, with the possible exception of output_of, which is being hashed out on the ticket (1307) linked above.

Annotation inference

* GO annotations should be inferred over is_a, part_of, and the regulates trio. Other relations used within GO should be ignored for the annotation inference purpose until further notice. As far as I know this is OK now.

* Desired behavior for FYPO is mostly documented on this wiki page (with output_of in Canto awaiting resolution): https://curation.pombase.org/pombase-trac/wiki/RelationsAndTransitivity
Briefly, for FYPO:
  * is_a and part_of work the same way as for GO;
  * FYPO has no regulates links;
  * A output_of B: all genes annotated to A should have annotation to B inferred;
  * A has_output B: all genes annotated to A should have annotation to B inferred;
  * A has_part B: all genes annotated to A should have annotation to B inferred.

I'll put a bit more on the website ticket about has_part (https://github.com/pombase/website/issues/89), since Val has just added comments there.

**Comment by ValWood** [comment]
corrected my comment above
has_out and output_of should mirror ~~Artemis~~ Canto behaviour

**Comment by kimrutherford** [comment]
> Other relations used within GO should be ignored for the annotation inference purpose until further
> notice. As far as I know this is OK now.

Just to be clear about what's happening in the website at the moment, we're using whatever Owltools infers, but only for these relations:
  is_a, part_of, regulates, has_part

And has_part is only used for FYPO.

It's very easy to add or remove relations so I've just added annotations inferred by output_of.

**Comment by mah11** [comment]
That all sounds pretty sensible so far.

**Comment by kimrutherford** [comment]
I think maybe this is done now?

> Just to be clear about what's happening in the website at the moment, we're using whatever Owltools infers, but only for these relations:
> is_a, part_of, regulates, has_part
> And has_part is only used for FYPO.

It's changed since I made that comment.  The current list is:
  - is_a
  - part_of
  - regulates
  - positively_regulates
  - negatively_regulates
  - has_part
  - output_of

(see: https://github.com/pombase/pombase-chado/issues/631#issuecomment-307030124)

The relations above are used when inferring annotation onto ancestors.  But the "Parents" section at the top right of term pages only shows links to direct parent terms via these relations: "is_a", "part_of", "regulates"

For example:
"multiseptate vegetative cell" (FYPO:0000118) is an "output_of" descendant of " abnormal cytokinesis" (FYPO:0000032) but "abnormal cytokinesis" isn't shown as a parent on the "multiseptate vegetative cell" page:
https://www.pombase.org/term/FYPO:0000118

If that's OK, I think we can close this issue.
