### ISSUE TITLE
more Artemis loading check for malformed qualifiers

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#618]
had "extension=during" instead of "annotation_extension=during"

was not reported in logs

**Comment by ValWood** [comment]
would
https://github.com/pombase/website/issues/665
find
"extension=during" instead of "annotation_extension=during"

**Comment by kimrutherford** [comment]
> would
> pombase/website#665
> find
> "extension=during" instead of "annotation_extension=during"

Unfortunately (again) the code was using the sub-qualifiers that it knew how to handle and ignore the others.  I've changed it so that only these qualifiers are allowed:

allele
annotation_extension
aspect
column_17
cv
date
db_xref
evidence
from
GOid
qualifier
residue
term

**Comment by kimrutherford** [comment]
You won't see the new warnings in the logs until Saturday morning.  Here they are.  The warnings about extensions like has_direct_input and during can be fixed by changing eg. "during=GO:0000092;" to "annotation_extension=during(GO:0000092)".  The warnings are sometimes duplicated due to a bug so SPBC2A9.07c for example should have only 3 warnings.

mRNA SPAC8C9.15c.1: unknown sub-qualifier: quailifier
mRNA SPAC323.05c.1: unknown sub-qualifier: has_direct_input
mRNA SPAC29B12.04.1: unknown sub-qualifier: qualifer
mRNA SPBC14C8.01c.1: unknown sub-qualifier: has_substrate
mRNA SPBC2A9.07c.1: unknown sub-qualifier: during
mRNA SPBC2A9.07c.1: unknown sub-qualifier: during
mRNA SPBC2A9.07c.1: unknown sub-qualifier: during
mRNA SPBC2A9.07c.1: unknown sub-qualifier: during
mRNA SPBC2A9.07c.1: unknown sub-qualifier: during
mRNA SPBC2A9.07c.1: unknown sub-qualifier: during
mRNA SPBC2A9.07c.1: unknown sub-qualifier: during
mRNA SPBC2A9.07c.1: unknown sub-qualifier: during
mRNA SPBC2A9.07c.1: unknown sub-qualifier: during
mRNA SPBC2A9.07c.1: unknown sub-qualifier: during
mRNA SPBC2A9.07c.1: unknown sub-qualifier: during
mRNA SPBC2A9.07c.1: unknown sub-qualifier: during
mRNA SPBC17D11.06.1: unknown sub-qualifier: qualiifer
ncRNA SPNCRNA.07.1: unknown sub-qualifier: extension
ncRNA SPNCRNA.07.1: unknown sub-qualifier: extension
ncRNA SPNCRNA.07.1: unknown sub-qualifier: extension
ncRNA SPNCRNA.07.1: unknown sub-qualifier: extension

**Comment by ValWood** [comment]
great thanks!

**Comment by kimrutherford** [comment]
Unfortunately there was a typo in the list of qualifiers so last night's qualifier problems file has lots of warnings about qualifiers that are fine.  I've fixed it for tonight's load.

**Comment by kimrutherford** [comment]
> I've fixed it for tonight's load

All fixed and the qualifier warning file looks better:
  https://curation.pombase.org/dumps/latest_build/logs/qualifier_problems.txt

**Comment by ValWood** [comment]
can close?
