### ISSUE TITLE
No evidence for genotype annotations from session b2890d84738249aa

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#623]
A few days ago I noticed a genotype annotation with no evidence.  So I've added a new chado check to report molecular_function, cellular_component, biological_process and fission_yeast_phenotype annotations that have no evidence.

When I run the check manually it finds over 100 annotations without evidence.  Oddly they are all from the same session:
  https://curation.pombase.org/pombe/curs/b2890d84738249aa/ro/

The evidence is there in Canto for that session so I suspect it's a loading problem.

**Comment by kimrutherford** [comment]
> Oddly they are all from the same session:

Sorry, it was a dodgy query that's fixed now.  They are all from the contig file not from a Canto session.  Does that make sense?  Are you expecting annotation with no evidence?

**Comment by kimrutherford** [comment]
> They are all from the contig file not from a Canto session

In case it helps, here's a list of those annotations including the allele name and gene name:
https://www.dropbox.com/s/5e822je4lvc3q44/annotation_with_no_evidence.txt?dl=0

They are all phenotype annotations.

**Comment by mah11** [comment]
Sorry, I think you had it right the first time. Those phenotype annotations were all made in Canto (by me), with evidence.

I don't remember whether there were any phenotype annotations in the contig files for that paper (PMID:14752051), but there aren't now, and there certainly wouldn't have been nearly as many as are in the Canto session.

**Comment by kimrutherford** [comment]
The ID (PMID:14752051) was a red herring caused by dodgy query.  Here are actual annotations with no evidence including the real PMIDs:
  https://www.dropbox.com/s/t1wj2w7f9ylo0w4/annotation_with_no_evidence_with_pmid.txt?dl=0

I added a chado check for annotation with no evidence so the chado checks are failing at the moment.

**Comment by ValWood** [comment]
are these all Artemis?
 there are  131 annotations /73 papers so it will take us a while to fix.

If there are artemis, could we insert a general evidence code (IMP) temporarily?

**Comment by ValWood** [comment]
These will all be fixed as they come through Canto.

**Comment by mah11** [comment]
> The ID (PMID:14752051) was a red herring caused by dodgy query.

OK, that makes a lot more sense. A quick spot-check of some of the PMIDs confirms that they haven't been curated in Canto. Only a handful of the phenotype annotations in the contig files have evidence specified. Many of the rest have evidence added at the Chado-loading stage using some configuration gubbins set out in #333, but that apparently doesn't cover absolutely everything.

I think there used to be log warnings about phenotype annotations without evidence, but then we suppressed them because there were a lot, they're all legacy, and we are working through them. If you now want to keep the check enabled in the meantime I bet I could come up with additions to the configuration for the annotations that are currently spawning errors.

(Val - these ARE phenotype annotations, so no, we can't us IMP as the evidence.)

**Comment by ValWood** [comment]
I presume there is an equivalent ECO code, or some general code that can be used as a stop gap?

**Comment by ValWood** [comment]
ok ignore that

**Comment by kimrutherford** [comment]
> A quick spot-check of some of the PMIDs confirms that they haven't been curated in Canto.

Yep, there are none from Canto.  You can't (or a least be able to) make an annotation in Canto without an evidence code.

> Many of the rest have evidence added at the Chado-loading stage using some configuration
> gubbins set out in #333,

I completely don't remember doing that.  :-)

> If you now want to keep the check enabled in the meantime I bet I could come up with
> additions to the configuration for the annotations that are currently spawning errors.

I think I'll add an optional flag to the chado check config so that an individual check can fail but not cause the overall Chado checking to fail - kind of a degrade from ERROR to WARNING.  So we will be able to see the annotations without evidence codes but the nightly_update will succeed anyway.

(The other alternative was to just comment out that Chado check, but then you wouldn't be able to see the output and we might forgot about it.)

**Comment by kimrutherford** [comment]
> I think I'll add an optional flag to the chado check config so that an individual check can fail but
> not cause the overall Chado checking to fail

I've made that change for the next load.

**Comment by mah11** [comment]
That makes sense.

It also looks like it wouldn't be a huge task to add automagic evidence to the config for a lot of them .. and it'll be Friday afternoon in an hour here ...

**Comment by mah11** [comment]
I have committed a bunch of additions to the auto_evidence_assignment configuration, which I think covers everything. I'm not sure they're all correct, since I just picked evidence by eyeballing the term names, but most of them should be OK and they'll all eventually be superseded in Canto anyway.

If the warnings all go away we could probably close this.

**Comment by kimrutherford** [comment]
> If the warnings all go away we could probably close this.

Thanks!  All fixed.  I've changed the chado check config so that it any annotation without evidence pops up in future, it will make the checks fail.  If that hard line plan turns out to be annoying I'll change it back to a warning.
