### ISSUE TITLE
new  quantitive expression file

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#673]
Duncan_29432178.txt

I think I did this one OK. I removed the control characters this time, but will check it loads tomorrow.

Also, I added the  very general code  ECO:0000006
as I think there is a mixture in here.

Most will be ribosome profiling and I could not find  a ECO for that (will request)
I think some might be western based on help-desk correspondence with Juan yesterday

**Comment by ValWood** [comment]
https://github.com/evidenceontology/evidenceontology/issues/165

**Comment by ValWood** [comment]
I found another file with the western blot one so everything with ECO:0000006
will need  converting to the new code when available.

**Comment by kimrutherford** [comment]
> Duncan_29432178.txt

I can't see that file in SVN.

**Comment by ValWood** [comment]
yup I forgot to check it in...

**Comment by kimrutherford** [comment]
Thanks.  Unfortunately there are a few problems in the file.  There are two copies for the annotation for "SPCC1393.08".  The first copy has spaces instead of tabs between the last three fields: "PMID:29432178   4896    20180309".  The second of the two copies has spaces instead of tabs between all fields.  And in all lines the "Type" column should be "RNA" or "protein".

**Comment by kimrutherford** [comment]
> first line seems OK

I see spaces instead of tabs on both lines.

The current code matches the original ticket:
https://github.com/pombase/pombase-chado/issues/311#issue-93728208
and the public docs:
https://www.pombase.org/documentation/qualitative-gene-expression-data-bulk-upload-format

I didn't know there where more possible terms.

> so can we allow the full list above to describe expression levels ?

Yep!  I won't have time to change it before the next load though.

Do any of those new terms match any of the current gene_ex CV terms?:
  https://curation.pombase.org/pombe/view/object/cv/55?model=chado
I want to avoid adding new terms where the meaning is the same but the term name is different.

I think the web code will cope with new terms but we should check after the terms are added.

**Comment by ValWood** [comment]
fixed now

> Yep! I won't have time to change it before the next load though.

no worries, I haven't approved the paper yet ....

**Comment by ValWood** [comment]
I don't fully understand this.
is it both "types" and the "qualifiers"

For  types we need

RNA level 
protein level 
transcription 
RNA degradation 
translation 
protein degradation

in here, I see

RNA level |   | gene_ex | 0011963 | 2
transcription |   | gene_ex | 0007535 | 0

The "2" above  (the only used items in this cv) are
so I think these somehow refer to "misc" but I'm not sure how

cdc27
PBO:0002125 | alternative transcripts | Hughes DA et al. (1992)
int6?
PBO:0000206 | deletion mutant expression profiling | Udagawa T et al. (2008) | 79


the qualititive expression files have these "types"
  1    (note to self fix required)
   1 4896 (note to self fix required)
  54 RNA
   6 protein
  31 translation (the new file)

and the quantitive have these types
14592 RNA
19856 protein

so I guess my question is, is that the correct cv, because it doesn't have "protein" in it?

**Comment by ValWood** [comment]
That's in the Duncan file
It's reporting a tax ID in field 3?

  1 4896
   1 Type
  31 translation

I can't see the problem (although there does seem to be something weird about  the field with the GO ID in  it in line 1.....

**Comment by ValWood** [comment]
I think the file you pointed to is "misc"

**Comment by ValWood** [comment]
ignore that it says gene ex. This is everything I used to add as "gene ex" in artemis.
Most of these are "gone"

It seems that the new gene expression are stored like this:
https://curation.pombase.org/pombe/view/object/feature/72341?model=chado


protein level [during] mitotic G1 phase |   | PomBase annotation extension terms | 0018335 | 2660
-- | -- | -- | -- | --
protein level [during] mitotic G2 phase |   | PomBase annotation extension terms | 0018333 | 2675
protein level [during] mitotic M phase |   | PomBase annotation extension terms | 0018384 | 2611
protein level [during] mitotic S phase |   | PomBase annotation extension terms | 0018544 | 2621


so the term, and the qualifier appear to be stored together?

**Comment by ValWood** [comment]
the int 6 above is from
/controlled_curation="term=gene expression, RNA level; qualifier=present; evidence=ECO:0005653; db_xref=PMID:11071923; date=20121118"

so that's an "old style" annotation. They seem to be stored differently?

**Comment by ValWood** [comment]
Actually, there are 3273 controlled curations for gene expression in artemis. I wonder why they don't show in the list? 

Val-Woods-MacBook-Pro:pombe-embl val$ grep "gene expression" *.contig  | grep "controlled" |wc
    3273 


I will check if we are displaying them

**Comment by ValWood** [comment]
1st one I checked SPAC212.02
/controlled_curation="term=gene expression, RNA level;
FT                   annotation_extension=in_presence_of(CHEBI:47600);
FT                   qualifier=increased; evidence=ECO:0000058;

is there.

Maybe int6 and cdc27 ones are incorrectly formatted in some way which is why they are treated differently?

**Comment by ValWood** [comment]
I can't see anything different about int6 and cdc27 gene_ex annotations....

**Comment by kimrutherford** [comment]
> I can't see the problem

I fixed some whitespace and checked the file back in.

> Actually, there are 3273 controlled curations for gene expression in artemis. I wonder why they don't show in the list?

I think that's because the list contains only the base terms.  Annotations to term+extension will be post-composed into new terms in this CV: https://curation.pombase.org/pombe/view/object/cv/19?model=chado

> so the term, and the qualifier appear to be stored together?

The term and extension(s) are composed into a new term.  The qualifier is stored separately.

I've added "transcription", "RNA degradation", "translation" and "protein degradation" to the gene_ex CV.  I'm running a load locally to see how it goes.

**Comment by kimrutherford** [comment]
> I'm running a load locally to see how it goes.

It's fine so I've started the nightly load.

**Comment by kimrutherford** [comment]
The load failed because I couldn't spell "RNA" successfully.  I've restarted it and it should finish by late morning.

**Comment by ValWood** [comment]
... it's a tricky one! I know.

**Comment by kimrutherford** [comment]
Looks like it loaded OK: http://pombase-dev.bioinformatics.nz/reference/PMID:29432178

It will be on the main site in 5 minutes.

**Comment by kimrutherford** [comment]
Looks OK: https://www.pombase.org/reference/PMID:29432178

**Comment by ValWood** [comment]
phew, great...
