### ISSUE TITLE
GO error checks

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#702]
Jenkins pipelines should no longer be used
GO picks up our files now 
(we should filter anything from GOC or GO_Central annotations from the file GO picks up if we want to reduce the logs)
However this won't work if this is the GO file we make available to our users. We will need a separate submission file.

I can't quite remember where we get the F-P inferences, or where we will get PAINT soon.

Anyway wrt the files we should be checking:

Current release
http://current.geneontology.org/reports/index.html

Daily snapshot (the one with the most recent data we submitted)
http://snapshot.geneontology.org/reports/index.html
http://snapshot.geneontology.org/

http://snapshot.geneontology.org/reports/gorule-report.html
	
	•	pombase-report.html    (contains everything)

I suspect Midori knows all of this since  we have no errors?

I'm not sure how we will get th PAINT and inferences since they will be injected into the GOgaf. I'm hoping GO will make these files avaiable for us in some way? @cmungall   Please can we have such files for import. It will make the round-tripping much easier

**Comment by ValWood** [comment]
Here are the rules. The status of each rule is listed. Some are not yet implemented.
https://github.com/geneontology/go-site/tree/master/metadata/rules

**Comment by kimrutherford** [comment]
Is there anything that needs to change at our end?

**Comment by ValWood** [comment]
Probably the  file we prepare for GO. not urgent though.

The rest is just for info but I think @mah11  is on it .....

**Comment by mah11** [comment]
> Is there anything that needs to change at our end?

In the short term, no. (We could strip out lines with IBA evidence, but that's optional because if we don't GOC won't load them when they take the file. The report just, well, reports that it happens.)*

Medium-term, GO has (at long last) started thinking about a time frame for switching to GPAD (and GPI) for submissions, so #276 will percolate up to high priority in the foreseeable future (but not next Tuesday, more like early next year). In the meantime we can continue producing GAFs as they are now.

*Kimberly clarified this on the GO annotation call last week, but the minutes from that call are nearly nonexistent so we're left with what i remember of it :P

**Comment by ValWood** [comment]
can close?
