### ISSUE TITLE
changes in transcription annotations

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#722]
I can't figure out what is causing this, so i need some help...

Historically, everything annotated to "regulation of process X", used to also be annotated to "process X"

This clearly isn't the case here for transcription:

![transcription](https://user-images.githubusercontent.com/7359272/56092261-a4494b80-5eb1-11e9-91e6-4966bcb022c9.jpg)

Although if this is a general phenomena I can't see why the slim isn't extremely adversly affected:
https://www.pombase.org/browse-curation/fission-yeast-go-slim-terms
(i.e things annotated to "regulates" would no longer be annotated to the process)

I'm baffled....

**Comment by kimrutherford** [comment]
I'm baffled too but mostly because this involves ontologies.  :-)

I had a look at one of the genes that's in the "regulation of transcription, DNA-templated" list but not in the "transcription, DNA-templated" list:
https://www.pombase.org/gene/SPAC140.03

OWLTools says these two terms are descendants of "regulation of transcription, DNA-templated" but not descendants of "transcription, DNA-templated":
 - chromatin silencing at centromere
 - chromatin silencing by small RNA

Here's the ancestry:
  https://www.ebi.ac.uk/QuickGO/services/ontology/go/terms/%7Bids%7D/chart?ids=GO:0006355%2CGO:0030702%2CGO:0031048

**Comment by mah11** [comment]
That actually makes a perverse kind of sense, because there are 78 genes found by

    (regulation of transcription, DNA-templated (GO:0006355) NOT transcription, DNA-templated (GO:0006351))

All are annotated to terms in the chromatin silencing branch of GO BP except for a few annotated to 'sterol regulatory element binding protein cleavage' (GO:0035103) (cdc48, dsc1-5, rbd2, rpn12, ubc4, ubr1, ufd1).

What does OWLTools say about 'carbon catabolite repression of transcription' (GO:0045013)? That one looks as though it has similar ancestry to GO:0006342, but genes annotated to it do inherit both GO:0006351 and GO:0006355 ... and I can't see a reason for the difference.

**Comment by ValWood** [comment]
Yes I think its a recent change in that now "regulation is not  inherited over regulation".

But I don't know when this change happened? I don't think it was announced, and it's a major change.....
@cmungall @pgaudet

@cmungall - I think this change will fix panther enrichment issues too.

**Comment by ValWood** [comment]
>What does OWLTools say about 'carbon catabolite repression of transcription' (GO:0045013)? That one looks as though it has similar ancestry to GO:0006342, but genes annotated to it do inherit both GO:0006351 and GO:0006355 ... and I can't see a reason for the difference.

I think it  is possible because "'carbon catabolite repression of transcription' (GO:0045013)" is is_a "regulation of transcription", but the others were  "regulation" of "regulation of transcription"

**Comment by ValWood** [comment]
There is something very sinister going on here:
We didn't change anything. Look at the totals for last week, vs this week.
This is an extreme example of the random flip-flopping I keep 'going -on' about. I'm convinced it is some arbitrary effect of  owl tools traversing different regulates paths. Beyond that I don't know what I am talking about. But  what I am seeing is a big issue.

I will transfer this to the GO tracker.

compare
how it was
![transcription](https://user-images.githubusercontent.com/7359272/56361714-f951ce00-61df-11e9-8433-605dc08f1826.jpg)

and how it is today
![flip flopping](https://user-images.githubusercontent.com/7359272/56361741-0a024400-61e0-11e9-8962-81e09295ef77.jpg)


Note that, despite the number of annotations to "regulation of transcription" being identical, the number of annotations to transcription changes radically.

**Comment by ValWood** [comment]
Mover to the GO tracker

**Comment by pgaudet** [comment]
Hi Val,

When is the first screenshot from?

As far as I know there has been no release since March 19th.

Pascale

Le jeu. 18 avr. 2019 à 3:17 PM, Val Wood <notifications@github.com> a
écrit :

**Comment by ValWood** [comment]
last week some time.....

**Comment by ValWood** [comment]
but it changes day by day. It will be different tomorrow! And we didn't annotate anything. I'll do another screen shot tomorrow.....

**Comment by kimrutherford** [comment]
I found something odd in the owtools output that might explain some of this.  I've commented here: https://github.com/geneontology/go-ontology/issues/17171#issuecomment-486005349

**Comment by ValWood** [comment]
since this seems to be a duplicate of 
https://github.com/pombase/pombase-chado/issues/678
closing

(even though Its an external issue I'll keep the first ticket open for now as a reminder)
