### ISSUE TITLE
Read and store diploid genotypes

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#734]
We need to change the Canto JSON loading code to handle the new format in: pombase/canto#1854

**Comment by kimrutherford** [comment]
> We need to change the Canto JSON loading code to handle the new format

As a first step I've changed the loading code to support the new format but only for haploid loci.  I wanted to do this in stages to reduce the chance that things will go wrong.

I'll work on diploid loading once we have some examples in Canto.

**Comment by kimrutherford** [comment]
> I'll work on diploid loading once we have some examples in Canto.

I made that comment ages ago.  We have lots of examples now so I better get on with it.  :-)

**Comment by kimrutherford** [comment]
I think I have plan for this now but I need help.  Each feature in Chado needs a SO term as a type and there isn't a "locus" term in SO.  I'm not sure what to use instead.  Any suggestions?  Or should we talk about this on Thursday?

**Comment by mah11** [comment]
I've had a think and a poke round SO, and thought of a couple questions:

- Can Chado take any SO ID, i.e. from anywhere in the ontology?
- Is the SO ID for loading diploids just for internal Chado use?

If yes to both, then I think we might be able to use `SO:0001028` "diplotype". Our use case isn't an exact fit to the SO definition or what I've just learned (in the last hour or two) about its usage, but for something behind the scenes it's probably close enough.

If the SO term is going to be very visible, it might be a minor hassle to explain "diplotype" and why we chose it. That may be worthwhile anyway, since I haven't thought up a better SO term so (haha) far. Let me know if Chado is restricted to a specific branch of SO that doesn't cover SO:0001028, and I'll try some more thinking.

**Comment by ValWood** [comment]
How is this

"http://www.sequenceontology.org/browser/current_svn/term/SO:0001028"
diplotype
A diplotype is a pair of haplotypes from a given individual. It is a genotype where the phase is known.

(i don't understand  the second sentence of the definition, but "is_a genotype"  sounds promising ?)
I found it by browsing under "sequence collection" and "variant collection", I wouldn't have found it by searching...

**Comment by ValWood** [comment]
I just saw your comment in my Inbox.

**Comment by kimrutherford** [comment]
> Can Chado take any SO ID, i.e. from anywhere in the ontology?

Yep.

> Is the SO ID for loading diploids just for internal Chado use?

Yep, it won't be visible on the website.  It's needed only for internal organisation of the alleles.  Which term we use isn't too critical for us but I'm thinking of future generations.  :-)

Let's talk about this at the meeting.  I made a diagram that I can point to while talking.

The current system for modelling genotypes and alleles in Chado is on the left.  We might need to move to something like the right hand diagram.

![locus-1](https://user-images.githubusercontent.com/90474/112402484-7b09e900-8d71-11eb-9a17-532c7bff6b1f.png)

**Comment by kimrutherford** [comment]
I think this is done now.  I'll check the changes on Saturday morning to make sure nothing is broken.

**Comment by ValWood** [comment]
brilliant! fingers x'd

**Comment by kimrutherford** [comment]
The Chado loading works so this can close.

**Comment by ValWood** [comment]
Excellent,  diploids have been a pain, that was a tricky one ;)
