### ISSUE TITLE
new disease associations

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#779]
SPBC1306.01c            MONDO:0012191           PB_REF:0000003  2020-05-24
SPCC1827.03c            MONDO:0013661           PB_REF:0000003  2020-05-24  

in
pombase_disease_associations_mondo_ids.txt 

don't seem to be appearing?

**Comment by kimrutherford** [comment]
The loader was failing with those two associations because there was a space after the gene ID, before the tab.

https://curation.pombase.org/dumps/builds/pombase-build-2020-05-28/logs/log.2020-05-29-00-16-05.disease_associations

I've fixed the loader to trim white space around the fields in the file so it should be OK tonight.

**Comment by ValWood** [comment]
Ah right I will be more careful. I was checking the tabbing, but not for additional spaces!
I checked the logs to but did not see these reported?

**Comment by kimrutherford** [comment]
> I checked the logs to but did not see these reported?

It's in the disease_association log file this: 
https://curation.pombase.org/dumps/latest_build/logs/

**Comment by ValWood** [comment]
of course, all warnings is all canto warnings...dah

**Comment by kimrutherford** [comment]
all_warnings.txt contains all the warnings from loading the contig files.

The files that start like "log.2020-05-29-00-16-05..." are the warnings from loading the non-contig data files.

**Comment by ValWood** [comment]
All good.
