### ISSUE TITLE
contig file logs missing from latest (09-03)

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-chado#790]
compare/contrast

https://curation.pombase.org/dumps/builds/pombase-build-2020-09-02/logs/ and
https://curation.pombase.org/dumps/builds/pombase-build-2020-09-03/logs/

The logs that report on the Artemis contig file loads are missing from the 2020-09-03 set, but are there in the older builds that I looked at.

**Comment by kimrutherford** [comment]
Hi.  Sorry about that.

There was a glitch that I fixed in the code the generates the website so I had to run the final load steps manually yesterday.  I wouldn't normally do that be I wanted to make this fix visible: pombase/pombase-chado#788

While running the manual steps, I forgot to copy the logs directory to the right place.  It will be back tomorrow.
