### ISSUE TITLE
happens during blah should never be comma separated

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#835]
log check for comma separated  "happens_during"

I spotted a number of comma separated  happens_during annotations:
( I don't know if this is all)

 happens_during(GO:0000085),happens_during(GO:0071472),has_input(PomBase:SPAC24H6.05),occurs_in(GO:0005737)
happens_during(GO:0007128),happens_during(GO:0030989)
happens_during(GO:0042149),happens_during(GO:0070314),has_input(PomBase:SPAC3G9.09c)

These shouldn't be comma separated, they should be pipe separated, they must be separate annotations because a gene product can't be in 2 places at the same time.
(itmight be better to enforce this by making cardinality '1'  in Canto)

tasks:
curation ticket to fix
Canto ticket to prevent

**Comment by mah11** [comment]
The Canto extension configuration already specifies cardinality `0,1` for all "during" extensions. (If any didn't, that would be a config ticket, not a Canto ticket). You could open a Canto ticket to check manually entered extensions (old or entered via admin text edit) but if these are the only ones it's probably not worth it.

> ... they must be separate annotations because a gene product can't be in 2 places at the same time.

Nothing ever happens *during* a place anyway.

Looking at these specific extensions ...

> happens_during(GO:0000085),happens_during(GO:0071472),has_input(PomBase:SPAC24H6.05),occurs_in(GO:0005737)

This one predates the clever extension interface in Canto. It also might be biologically sensible -- it's during a phase and during a response:

	rad24, GO:0140311 protein sequestering activity has_input cdc25, occurs_in cytoplasm, happens_during mitotic G2 phase, happens_during cellular response to salt stress.

PMID:15629716

> happens_during(GO:0007128),happens_during(GO:0030989)

Not sure how this one happened, since the session came in after clever extension handling; maybe the approver added all or part of the extension in text? Anyway, the biggest problem with it is that it's on an annotation to GO:0030989! Process happens during itself, yay.

I've fixed it. PMID:28292899

> happens_during(GO:0042149),happens_during(GO:0070314),has_input(PomBase:SPAC3G9.09c)

This session also predates Canto expression cleverness; it has two annotations with two happens_during apiece, and they might be OK:

	hri1 GO:0004694	eukaryotic translation initiation factor 2alpha kinase activity  has_input tif211, happens_during G1 to G0 transition, happens_during cellular response to nitrogen starvation
	hri2 GO:0004694	eukaryotic translation initiation factor 2alpha kinase activity  has_input tif211, happens_during G1 to G0 transition , happens_during cellular response to glucose starvation

It might be worth a look, though, because the annotations have comments that don't exactly match the extensions.
PMID:23687372

I found 4 more in the GAF, which I'm checking now.

**Comment by mah11** [comment]
The last 4 are also during a phase and a response - 3 from one paper Jacky did recently (admin edits?), and the other predating the extension interface:

PMID:8121488

	rum1 GO:0007089 traversing start control point of mitotic cell cycle happens_during mitotic G1 phase, happens_during cellular response to nitrogen starvation
	rum1 GO:0031568 mitotic G1 cell size control checkpoint signaling happens_during mitotic G1 phase, happens_during cellular response to nitrogen starvation
	cdc2 GO:0031568 mitotic G1 cell size control checkpoint signaling happens_during mitotic G1 phase, happens_during cellular response to nitrogen starvation


PMID:12960401

	cds1 GO:0004672 protein kinase activity  happens_during cellular response to UV, happens_during mitotic G1 phase

**Comment by ValWood** [comment]
PMID:23687372
checked this one, removed the comments, they were the wrong way around

**Comment by kimrutherford** [comment]
Is there anything more to do here?

**Comment by ValWood** [comment]
It probably can be.

I still get confused about the difference between happens_during and occurs_during.

@mah11 could you let me know where I can look this up (I'm also confused about  where the available list is maintained -do you know?)

**Comment by mah11** [comment]
>  the difference between happens_during and occurs_during.

The difference is that `happens_during` is a real relation and occurs_during isn't.

> where the available list is maintained - do you know?

I did a bit of digging and found it:
https://github.com/geneontology/go-site/blob/master/metadata/extensions-constraints.yaml

**Comment by ValWood** [comment]
Is it weird that the PomBase prefixes are never included here?

**Comment by mah11** [comment]
> Is it weird that the PomBase prefixes are never included here?

Where is the "here" in this question?

**Comment by ValWood** [comment]
In the name sp[aces for the constraints

e.g.

- relation: has_input
  namespaces:
    - MGI
    - WB
    - PR
    - UniProtKB
    - CHEBI
    - PR
    - SO
    - CL
    - GO
    - WBbt

**Comment by mah11** [comment]
OK, that makes it not a question for this tracker.

**Comment by ValWood** [comment]
I think this is OK, we fixed the violations and new examples should not occur (unless the text editing interface is used)
