### ISSUE TITLE
Investigate the new warnings in qualifier_problems.txt

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#844]
There are a bunch of new warnings like this in `qualifier_problems.txt`: 

mRNA SPBC460.05.1: failed to add annotation extension to SPAC1F7.05 <-> RNA absent: storing feature_cvterm from SPAC1F7.05 to RNA absent [during] G2/M transition of mitotic cell cycle - failed to store feature_cvterm: that annotation has already been stored in Chado with properties:  evidence: "northern assay evidence used in manual assertion"  from session: UNKNOWN

These all involve RNA level terms so I suspect they are caused by a code or configuration problem rather than being real curation warnings.

**Comment by mah11** [comment]
The other clue is that these warnings just started appearing a few days ago. I don't *think* we've changed that many RNA level annotations in the right time-frame.

**Comment by kimrutherford** [comment]
Thanks for that reminder.   It looks look the fix for pombase/website#1727 is what's causing the problem.  All the genes it's complaining about have multiple transcripts.

**Comment by kimrutherford** [comment]
I've dug into this.  It looks like the problem is that the same annotation is on both CDSs in the contig file, but in Chado gene expression annotation is attached to gene features rather than transcript features.  So the warnings are correct, the annotation is duplicated.  We're seeing the warnings now because we have stopped ignoring annotation on the .2 and .3 transcripts - we now store the annotation from all CDS features.

The simplest solution is to remove the gene expression annotation except on the .1 transcript.

But is gene expression actually transcript specific?  Should we be calling it transcript expression?

**Comment by ValWood** [comment]
This seems like the same situation as
https://github.com/pombase/website/issues/1799
My feeling is that if we have no isoform-specific data we attach the annotation to the gene ID

**Comment by mah11** [comment]
> But is gene expression actually transcript specific?

It can be, and we have different RNA level annotations on each transcript isoform for our old friend tco1. But for the vast majority of pombe genes we don't have isoform-specific expression annotations, so my suggestion is to modify your simple solution slightly:

> The simplest solution is to remove the gene expression annotation except on the .1 transcript.

Let's do this for everything where the annotations are the same for all transcripts. Where they're different (as for tco1), keep all of the annotations, and keep them associated with the correct isoform. I realize that means adding the "transcript ID" column to the gene exp display at least for some genes, so it's that bit less simple, but it's for a good cause.

And all that said, ...

> Should we be calling it transcript expression?

No, I think we should stick with "gene expression" for displays, because that covers both RNA and protein level annotations (as it should, since we display both in the same section; and the protein level annotations are all made without trying to figure out which transcript isoform(s) was/were translated to get the protein). It's also well understood by all sorts of users.

**Comment by kimrutherford** [comment]
> The simplest solution is to remove the gene expression annotation except on the .1 transcript.

I've done that.

SPBC2D10.10c only has gene expression annotation on the .2 and .3 transcripts.  Could one of you two decide what to do in that case?

**Comment by ValWood** [comment]
What is the source of the annotation for SPBC2D10.10c?

**Comment by ValWood** [comment]
It is also confusing in these situations to have 3 alternative translations, since there is only one translation.

**Comment by ValWood** [comment]
fixed.
Can this be closed?

**Comment by kimrutherford** [comment]
> Can this be closed?

Yep!  They're all fixed and the qualifier_problems.txt log file now only has two lines.
