### ISSUE TITLE
Column 17 "Gene Product Form ID" in GPAD/GPI files

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado#851]
Hi Midori.

It looks like I forgot to include the col 17 IDs in the GPAD/GPI files.  Could you remind me where they go?

Thanks.

**Comment by mah11** [comment]
This turned out to be a "good" question, in the sense that the answer appears to be a bit complicated and slightly annoying.

Basically, GAF column 17 doesn't have a direct equivalent in GPAD alone. Instead, it relies on the GPAD+GPI combo:

- Put the column 17 PR:nnn ID in GPAD column 1
- Add a GPI entry for the column 17 protein form, with the PR ID in column 1 and the PomBase ID in column 7 or 8 or both -- 7 is for a gene ID, 8 is for a protein, per this comment:

> 'Encoded By' to capture a gene ID, and 'Parent Protein' to capture the gene-centric reference proteome accession for protein isoforms or peptides derived from proteolytically processed proteins.

(from Kimberly, https://github.com/geneontology/go-annotation/issues/2864#issuecomment-609814311)

**Comment by kimrutherford** [comment]
Yeah, I had a look at the GPI/GPAD docs before I made the issue and I made me wonder if an unpleasant solution would be needed.

Thanks for tracking down the answer.

The writing code will need quite a rearrangement to implement this.  Luckily there is no rush for the GPI/GPAD files.

**Comment by kimrutherford** [comment]
Hi Midori.  I've had a go at this following your advice.  The results are in the usual place:
https://curation.pombase.org/dumps/latest_build/misc/gene_product_information_taxonid_4896.tsv
https://curation.pombase.org/dumps/latest_build/misc/gene_product_annotation_data_taxonid_4896.tsv

> 8 is for a protein

I've just re-read what you should and I missed that bit.  Currently both columns 7 and 8 have the gene ID.  I'll fix that for tomorrow.

**Comment by mah11** [comment]
Those are shaping up well. Nothing (else) leaps out to me as needing a fix.

**Comment by kimrutherford** [comment]
> I've just re-read what you said and I missed that bit. Currently both columns 7 and 8 have the gene ID. I'll fix that for tomorrow.

That's fixed now.

> Those are shaping up well. Nothing (else) leaps out to me as needing a fix.

Cheers.  I'll close this and we can open new issues for other problems.
