### ISSUE TITLE
output GAF: warnings about gp-to-term relation

### ISSUE THREAD

**Issue by mah11** [pombase/pombase-chado#872]
Relevant to the "GO-style" v2.2 GAF ...

In the current (2021-11-03) [snapshot report](http://snapshot.geneontology.org/reports/pombase-report.html), there are a bunch of warnings about annotations using the wrong gene product-to-term relations in column 4. Example:

    WARNING - Violates GO Rule: GORULE:0000061: Found violation of: Only certain gene product to term relations are allowed for a given GO term but was repaired: RO:0002432 should be one of BFO:0000050 -- PomBase SPAC12B10.01c SPAC12B10.01c is_active_in GO:0032991 GO_REF:0000051 NAS C HECT-type ubiquitin-protein ligase E3, implicated in negative regulation of ubiquitinated chromatin formation (predicted) SPAC31F12.02c|SPAC637.15c protein taxon:4896 20090126 PomBase

There are 39 warnings, but they only involve two GO IDs (GO:0032991 and GO:0042788). It's not a huge deal because the report says they get repaired, but I'm logging it here since they come up. If you have questions, I can't promise I'll be able to help but I'm happy to try.

**Comment by kimrutherford** [comment]
I've been trying to parse: https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000061.md

I think it says:

   - `GO:0005575 "cellular component"` always use `RO:0002432 "is_active_in"` (we don't have any of those annotations)
   - `GO:0032991 "protein-containing complex"`, or `is_a` descendant always use `BFO:0000050 "part of"`
   - otherwise it can be any of: `RO:0001025 "located in"` and `RO:0002432 "is_active_in"`, and `RO_0002325 "colocalizes_with"`

I can see a bug in the code: it's only checking descendants of `GO:0032991` not `GO:0032991` itself.  I've fixed that which should fix the warnings about `GO:0032991` annotations.  I'll check on Friday.

I'm not so sure about the `GO:0042788` annotations.  The gorule says the `BFO:0000050 "part of"` should be applied to `GO:0032991` and its subclass descendants, which I think means `is_a` descendants?  The output from OWLTools in Chado has `GO:0042788` as a `part_of` descendant of `GO:0032991`.  Because of that the code is not applying `BFO:0000050 "part of"` to `GO:0042788`.

https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0042788

Have I misunderstood or is the warning from the snapshot wrong?

It's easy to change the code to look for `part_of` descendants of `GO:0032991` instead (or as well as?) of `is_a` descendants.

**Comment by mah11** [comment]
> I've fixed [not checking `GO:0032991` itself] which should fix the warnings about `GO:0032991` annotations.

Thanks, and glad that part was straightforward.

>  The gorule says the `BFO:0000050 "part of"` should be applied to `GO:0032991` and its subclass descendants, which I think means `is_a` descendants?

Yes, that sounds like the correct interpretation to me.

> The output from OWLTools in Chado has `GO:0042788` as a `part_of` descendant of `GO:0032991`.

That's correct too ... although the full ancestry of 'GO:0042788` is intriguing:
![GO42788](https://user-images.githubusercontent.com/5196259/140298892-14856307-5fb1-41ad-9151-f93117db20cc.png)


There's a [ticket](https://github.com/geneontology/go-ontology/issues/21143) open that shows that the question has been raised with GO, so ...

> Because of that the code is not applying `BFO:0000050 "part of"` to `GO:0042788`.

Don't bother changing the code, at least for now. Perhaps I'll comment on the GO ticket; in any case, it's possible that GO may change the parentage of `GO:0042788` and/or `GO:0005840`, and in the meantime their pipeline "repairs" the annotations to use the gp-to-term relation they expect.

**Comment by kimrutherford** [comment]
> Don't bother changing the code

OK, thanks.  As long as the GO pipeline is fixing it, it's not urgent.

**Comment by ValWood** [comment]
Nothing to do here for now...

**Comment by ValWood** [comment]
Can this be closed or is there still something to do?

**Comment by kimrutherford** [comment]
> Can this be closed or is there still something to do?

I think we'll eventually need to do some local fixes.  The GO pipeline is fixing things for now so I think we should close this and ignore the problem until the pipeline starts reporting errors for this, if it ever does.
