### ISSUE TITLE
duplicate description reported, but does not appear to be a duplicate as 'unknown' description

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#875]
SPAC2G11.12	rqh1-K547A	29ac2c8c97f2cc6c	K547A	rqh1-hd	e4b31ea722f9e274

but, in session
e4b31ea722f9e274
rqh1-hd is "unknown" not K54

<img width="340" alt="Screenshot 2021-11-04 at 14 34 06" src="https://user-images.githubusercontent.com/7359272/140333393-a0577500-c23a-44fe-b15d-72d99f76a932.png">
7A

I thought the list
alleles with the same description that have different names - CHECK FAILURE:  expected 0 but got 282

was only for alleles with explicitly the same description?

**Comment by mah11** [comment]
Hmm, yes, that is weird. The check hasn't included `unknown` generally since #746 got fixed, and if it had completely reverted, there would be a couple thousand spurious entries (as there were back then).

**Comment by kimrutherford** [comment]
I think the problem is that the allele with name "unknown" and description "K547A" from e4b31ea722f9e274 is merged with "rqh1-hd(K547A)" from 5fff5e70e49d4274 (because of #531).

The duplicate description report is only showing e4b31ea722f9e274 but it should show all the sessions that are the sources of the alleles.  I've changed the query to do that.  Sorry, I should have thought of that when I created that Chado check.

I also noticed that every duplication is reported twice.  Like:

```
 SPAC23C4.19   spt5(T1E)7  8a66efe1aac64683   T1E mutations within the CTR   spt5-T1E     acd89b47e1b47f21
 SPAC23C4.19   spt5-T1E    acd89b47e1b47f21   T1E mutations within the CTR   spt5(T1E)7   8a66efe1aac64683
```

The second is the same as the first, but with the order of alleles and sessions swapped.  I've fixed that so now that it only reports each duplication once.

Here's an example of the new output: https://curation.pombase.org/kmr44/dup_description_report.tsv

I committed the query fixes before tonight's load started so the .chado_checks log file will be updated in the morning.

**Comment by ValWood** [comment]
yesterday
alleles with the same description that have different names - CHECK FAILURE:  expected 0 but got 282
today
alleles with the same description that have different names - CHECK FAILURE:  expected 0 but got 136

getting there! I'm chipping away at 10-20 a day, should all be sorted in the next 2 weeks

**Comment by ValWood** [comment]
I don't think we need this ticket?
