### ISSUE TITLE
support multiplicity extension values in modification files

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#880]
I'm a bit confused by this one, I'm not aware of any use of transcript IDs in modification files, and only 
 some files seem to be affected?

https://curation.pombase.org/dumps/latest_build/logs/log.2021-11-16-21-39-46.modification

@mah11  could you take a look? Assigning also to @kimrutherford

**Comment by mah11** [comment]
This has nothing to do with transcript isoform IDs. The IDs that the loader can't parse are the multiplicity values in the file of TOR phosphoproteome data (extensions a la `multiplicity(1)`). So Kim needs to do whatever magic will allow `multiplicity` to be used with integers as the "range".

Only one file -- PMID_34296454_modifications.tsv -- is affected, because it's the only one with `multiplicity()` extensions.

**Comment by kimrutherford** [comment]
I've fixed the loader so that multiplicity() is an accepted extension relation.  I'll now check that the website code is OK with it.

**Comment by kimrutherford** [comment]
> I'll now check that the website code is OK with it.

Seems OK.  Let me know if it needs any changes.  The new dataset should be on the main site on Wednesday morning.

![multiplicity-1](https://user-images.githubusercontent.com/90474/144964263-674b9e3b-e643-4220-b562-429cca048ffe.png)
