### ISSUE TITLE
lsd1 SPBC146.09c

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#940]
has
GO:0006633 | fatty acid biosynthetic process | NAS | GO_REF:0000051

but  i can't trace the source of this annotation.
It isn't in  the legacy GO data file, or any of the
external_data/external-go-data/
as far as I can see

**Comment by kimrutherford** [comment]
The annotation comes from `pombe-embl/external_data/external-go-data/go_proc.txt`:
```
PomBase     SPAC4A8.11C     FAS2            GO:0006633      GO_REF:0000051  NAS             P       FAS2    LSD1    gene    taxon:4896      20090126  PomBase
```

Unfortunately it's picking up the "LSD1" in the synonyms columns in preference to the systematic ID.  I implemented it that way because it makes sense for GOA GAF files.  It's not so clever for non-GOA GAF files.

I'll add an option for the GAF reading code to ignore the synonyms for the GAF files in `pombe-embl/external_data/external-go-data/` and only use the systematic ID column.

**Comment by kimrutherford** [comment]
> I'll add an option for the GAF reading code to ignore the synonyms for the GAF files

I've added that so the synonym column is ignored for PomBase GAF files.  I'll see how that goes in tonight's load.

**Comment by kimrutherford** [comment]
The lsd1 annotation is now gone and GO:0006633 is correctly annotated on fas2.

I can't see any extra warnings or errors in the log file.
