### ISSUE TITLE
Fix case of existing markers in  genotype backgrounds

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#980]
@manulera  what should the case be for these. Upper case?

 - kanR
   - KanR
   - hphR
   - natR
   - KanMX
   - KanMX6

**Comment by manulera** [comment]
Hi Val,

Can't really say to be honest, they are in all formats out there. If we were being pombe-like I guess it would be kanMX6 (that's how it's written in Jurg's PCR targeting paper and in many plasmids, but the one with capitalised first letter is not uncommon).

Also since you mentioned, I also checked something I had been thinking about for a while. Some people have markers annotated as kanMX4, and I was wondering what the difference is. I downloaded a bunch of KanMX4 from addgene, and they all seem to be identical. See alignment below if you want:

https://www.ebi.ac.uk/Tools/services/web/toolresult.ebi?jobId=clustalo-I20220531-095336-0266-18098355-p1m&analysis=alignments

**Comment by ValWood** [comment]
OK, we can probably make a decision to standardize on lower case?
This will require a global replace to repair:



KanR -> kanMX
KanMX6 -> kanMX

I will add the others to this list.

We can use this to create an 'exogenous marker genes' synonyms file. We will  collect these synonyms collection outside of Canto as it's only required as a reference file (we won't display these synonyms). Then can be a shared resource  with Genestorian.

We can cover the syntax for markers as a section in the planned  "allele syntax" publication  (we will mandate the nomenclature - can get approval from  SAB and GNC). 

Let's make things easier!

**Comment by kimrutherford** [comment]
> I will add the others to this list.

So should I wait a bit before I start on this issue?

**Comment by ValWood** [comment]
Yes we should just quickly discuss first to check

**Comment by kimrutherford** [comment]
Hi @ValWood

> KanR -> kanMX
> KanMX6 -> kanMX
>
> I will add the others to this list.

Was there anything else to add to that list?
