### ISSUE TITLE
has_substrate vs has_input

### ISSUE THREAD

**Issue by ValWood** [pombase/pombase-chado#997]
I just fixed:

warning in 6e4bd6933c454826: can't find relation cvterm for: **has_substrate** in these CVs: relationship go/extensions/gorel fypo_extension_relations PSI-MOD_extension_relations external fission_yeast_phenotype

but I thought you had globally replaced all of these? Can you check because I'm worried that the logs are only reporting one example, and I will need to keep on fixing them?

**Comment by kimrutherford** [comment]
> but I thought you had globally replaced all of these? Can you check because I'm worried that the logs are only reporting one example, and I will need to keep on fixing them?

I did but I forgot to update the annotation extension configuration too.  So those `has_substrate` extensions were added after I changed `has_substrate` to `has_input`

https://github.com/pombase/pombase-config/blob/master/canto/annotation_ex_config/GO_MF_A_E_config

Should I change the extension config in all cases so that `has_input` is used instead of `has_substrate`?

**Comment by kimrutherford** [comment]
I checked and there are 5 annotation made with `has_substrate` extensions.  Three in:
https://curation.pombase.org/pombe/curs/a09af17a2956146d

One in:
https://curation.pombase.org/pombe/curs/721bf4355105bfb4

And one in https://curation.pombase.org/pombe/curs/260925d9ac1a773d

**Comment by ValWood** [comment]
> Should I change the extension config in all cases so that has_input is used instead of has_substrate?
Yes please ;)

**Comment by kimrutherford** [comment]
> Should I change the extension config in all cases so that has_input is used instead of has_substrate?

Done!  And I've updated Canto with the new configuration.

**Comment by kimrutherford** [comment]
I think this is done.
